### ISSUE TITLE
Add --kill-on-exit option to proot

### ISSUE THREAD

**Issue by romainreuillon** [indigo-dc/udocker#100]
`--kill-on-exit` of proot kills the tracee proot exists. It will avoid udocker to hang when a child process doesn't end. (It doesn't cover the case when a tracee is attached to init with nohup though, but work resonably well for child processes).

**Comment by jorge-lip** [comment]
Are there any known side effects of using this flag by default ?
If not, why is this not set by default in PRoot ?

**Comment by romainreuillon** [comment]
I am not sure, I used it only through udocker because udocker was hanging at the end of an execution.

**Comment by romainreuillon** [comment]
I looked at the code and I think they choose it not to be the default behaviour only to be conservative from the old behaviour.

**Comment by jorge-lip** [comment]
Added to devel branch
