### ISSUE TITLE
udocker installation fails

### ISSUE THREAD

**Issue by sustr4** [indigo-dc/udocker#103]
Following the installation guide at https://github.com/indigo-dc/udocker/blob/master/doc/installation_manual.md udocker installation currently fails: the proper version of udocker 1.1.1 seems not to be present in the download repository:

    $ ./udocker install
    Info: creating repo: /home/sustr4/.udocker
    Info: installing 1.1.1
    Info: installing from: http://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/tgz/udocker-    1.1.1.tar.gz
    Error: in download: HTTP/1.1 404 Not Found
    Info: installing from: https://owncloud.indigo-datacloud.eu/index.php/s/AFImjw8ii0X72xf/download

**Comment by jorge-lip** [comment]
I thanks, I'm waiting for Cristina to add the artifacts to the INDIGO repository, hopefully this week.
Meanwhile it can download automatically from the other locations, in your case it downloaded
from the INDIGO owncloud.
