### ISSUE TITLE
Can I run udocker inside a container?

### ISSUE THREAD

**Issue by frezbo** [indigo-dc/udocker#105]
I want to run some basic stuff inside a container and was thinking if I could run udocker in a container without exposing the docker socket to it.

**Comment by jorge-lip** [comment]
udocker is unrelated to the Docker socket. You can run udocker inside Docker.

**Comment by frezbo** [comment]
@jorge-lip thanks for the response, I tried running udocer inside both an ubuntu and an alpine container, both cases secoomp denies getting a shell, this is the error: 
```

**Comment by jorge-lip** [comment]
Docker (not udocker) tries hard to prevent processes inside containers to gain access to the host, several functionalities needed by the P1 and P2 modes of udocker are disabled by default in Docker. You can try to use the Fn modes  as explained in https://github.com/indigo-dc/udocker/issues/106 or
Start Docker (not udocker) as a privileged container like: run --privileged.

**Comment by frezbo** [comment]
@jorge-lip running as privilged would be a bad idea, I would still go with by just giving it access to the required syscalls, but running in Fn mode kind of solved my problem, as I'm not trying to run udocker as fully isolated in a container, but at least some namespace separation. This issue may be closed if you feel so, a big thanks for the maintainers on the prompt and fast response.

**Comment by jorge-lip** [comment]
Sure, if you want some level of separation/protection and really want to use Docker then you should run udocker inside Docker with the Fn modes. The udocker R1 mode uses runC and user level namespaces thus also providing some separation (currently not as complete as Docker). With this mode you may be able to run and have separation without using Docker, but only works in very recent kernels (notably does not work with CentOS 6 and 7).
