### ISSUE TITLE
How to build for alpine

### ISSUE THREAD

**Issue by frezbo** [indigo-dc/udocker#106]

**Comment by jorge-lip** [comment]
udocker is currently supported for CentOS, RH, Fedora, Ubuntu.
Execution of udocker inside Alpine is currently not supported, but feedback or contributions are welcome.

**Comment by jorge-lip** [comment]
Having said you can try the following once inside the alpine container running in Docker.

apk update
apk add curl
curl https://raw.githubusercontent.com/indigo-dc/udocker/devel/udocker.py > udocker
chmod a+rx udocker
 
apk add python
apk add tar
apk add findutils
apk add file
./udocker --allow-root install
./udocker --allow-root pull ubuntu:16
./udocker --allow-root create --name=c6 centos:centos6
./udocker --allow-root setup --execmode=F1 c6
./udocker --allow-root run --nosysdirs  c6



Notice that running an Alpine container inside udocker itself does not yet work in 
the Fn execution modes which are the only ones that can work inside Docker.
The default Pn modes do support Alpine containers execution but unfortunately
 these modes require PTRACE which does not work inside Docker. We are 
working to support Alpine containers execution in the Fn modes.

**Comment by frezbo** [comment]
Thanks @jorge-lip i will try this out and let you know, super happy for the fast response and how the maintainers are enthusiastic on maintaining the project
