### ISSUE TITLE
Please add support for "--no-trunc --all" to images subcommand matching docker's output

### ISSUE THREAD

**Issue by mr-c** [indigo-dc/udocker#108]
Heading is
```
REPOSITORY TAG IMAGE ID  CREATED SIZE
```
For example, `cwltool` only cares about the values of the first three columns. The first two column values can be `<none>`.

`--no-trunc` and `--all` could be ignored, but would be nice if they didn't cause an error

**Comment by jorge-lip** [comment]
Added to 1.1.2
