### ISSUE TITLE
Image[@digest]

### ISSUE THREAD

**Issue by joshua-gould** [indigo-dc/udocker#112]
Allow images to be specified using digests. For example, udocker run alpine@sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0 date

**Comment by TMiguelT** [comment]
This is important for some engines that seem to use this syntax by default (e.g. [Cromwell](https://github.com/broadinstitute/cromwell))

**Comment by mariojmdavid** [comment]
would imply major refactoring and implementation
not in immediate plans
