### ISSUE TITLE
Did you considered proposing PRoot patches to the upstream?

### ISSUE THREAD

**Issue by AkihiroSuda** [indigo-dc/udocker#114]
https://github.com/jorge-lip/PRoot/commit/10ca3e88dc1d2e2b45439b181a168af6b4053b91

@jorge-lip Did you considered proposing your PRoot patches to the upstream (proot-me/PRoot)?

**Comment by jorge-lip** [comment]
Yes there are pull requests open in PRoot for these patches.
Unfortunately there is still an issue with the patch for PTRACE+SECCOMP
that sometimes fails.
