### ISSUE TITLE
Use pex to distribute a single executable file

### ISSUE THREAD

**Issue by mr-c** [indigo-dc/udocker#116]
Dear maintainers,

I appreciate that `udocker` is a single file for ease of installation, but its monolithic nature makes contributions difficult.

I suggest that `udocker`
1. be split into multiple files
2. be packaged using [`pex`](https://pex.readthedocs.io/en/latest/whatispex.html) for single file distribution. `pex`d archives are compatible with any Python 2.6+ system, no setup required.
3. Over time some of the functions can be replaced with 3rd party convenience libraries.

I would be happy to assist with the above.

**Comment by yuvipanda** [comment]
I would also be happy to assist with this suggestion if that's something the maintainers would like :)

**Comment by yuvipanda** [comment]
We can also ship the tarball with the pex file, thus reducing dependency on the tarball being hosted.

**Comment by mariojmdavid** [comment]
work ongoing (mostly done) in branch devel3

**Comment by mariojmdavid** [comment]
the devel3 is pre-release, distributed as a tarball and simple instructions, also the unit tests have been split
this issue will be closed
