### ISSUE TITLE
Error: proot executable not found

### ISSUE THREAD

**Issue by gijzelaerr** [indigo-dc/udocker#117]
Hi!

I can't get udocker to work anymore. when I run:
```
$ cd ~
$ rm -rf .udocker
$ curl https://raw.githubusercontent.com/indigo-dc/udocker/master/udocker.py > udocker
$ chmod u+rx ./udocker
$ ./udocker install
$ udocker -D run fedora
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: *\\/\\.wh\\.*: Not found in archive
tar: Exiting with failure status due to previous errors
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: *\\/\\.wh\\.*: Not found in archive
tar: Exiting with failure status due to previous errors
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: *\\/\\.wh\\.*: Not found in archive
tar: Exiting with failure status due to previous errors
bin
boot/
dev/
etc/
etc/.pwd.lock
etc/DIR_COLORS

[....]

var/spool/mail/
var/tmp/
var/yp/
Warning: no command assuming: ['/bin/bash', '-i']
Error: proot executable not found
```
proot is available as an executable on my host. I also tried the develop branch. Any suggestions?

**Comment by jorge-lip** [comment]
Please check 
- the content of $HOME/.udocker/bin and whether proot is there
- check if you have UDOCKER_ env variables set       " env | grep UDOCKER "
  if so you may need to delete or override then
- check if you have udocker.conf files in /etc if so you may need to override the
  host installation by setting environment variables

Try
- rerun the installation    ./udocker -D install --force

If not in which operating system and kernel version are you trying to run ?

**Comment by gijzelaerr** [comment]
```
gijs@tina:~
λ  ls -al ~/.udocker/bin
ls: cannot access '/home/gijs/.udocker/bin': No such file or directory
❗
gijs@tina:~
λ  ls -al ~/.udocker
total 20
drwxrwxr-x  5 gijs gijs 4096 Jan 15 11:05 .
drwxr-xr-x 28 gijs gijs 4096 Jan 15 14:19 ..
drwxrwxr-x  7 gijs gijs 4096 Jan 15 11:12 containers
drwxrwxr-x  2 gijs gijs 4096 Jan 15 11:06 layers
drwxrwxr-x  3 gijs gijs 4096 Jan 15 11:05 repos
gijs@tina:~
λ   env | grep UDOCKER
gijs@tina:~
λ  ls -al /etc/udocker.conf
-rw-r--r-- 1 root root 90 Nov 27 12:29 /etc/udocker.conf
```
There we go! Turns out the `udocker` Debian package was also installed on this system. Upon removal of this package I can succesfully start containers.

**Comment by mr-c** [comment]
I would say "a `udocker` Debian package" as there is not (yet) an official `udocker` Debian package: https://packages.debian.org/search?keywords=udocker :-)

**Comment by mr-c** [comment]
Perhaps a notice about which configuration file is used should be printed?
