### ISSUE TITLE
Help interpreting error on "python udocker pull [image]"

### ISSUE THREAD

**Issue by skilbjo** [indigo-dc/udocker#121]
Hi there 👋 

I am running this script on AWS Lambda:

```
export HOME=/tmp
export UDOCKER_DIR=/tmp
export UDOCKER_BIN=/tmp
export UDOCKER_LIB=/tmp
export UDOCKER_CONTAINERS=/tmp

cd /tmp

curl https://raw.githubusercontent.com/indigo-dc/udocker/devel/udocker.py >udocker
chmod +x ./udocker

python udocker version # prints -> version: 1.1.1
# also prints -> tarball: https://owncloud.indigo-datacloud.eu/index.php/s/AFImjw8ii0X72xf/download https://cernbox.cern.ch/index.php/s/VC7GuVWA7mYRAiy/download http://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/tgz/udocker-1.1.1.tar.gz

# Pull image
python udocker pull quay.io/skilbjo/iris:x86 # failure occurs here
# failure occurs also with a more mainstream image like ubuntu:17.10
```

and here is my stack trace

```
File "udocker", line 6725, in <module>
sys.exit(Main().start())
File "udocker", line 6638, in __init__
Config().user_init(self.cmdp.get("--config=", "GEN_OPT"))
File "udocker", line 322, in user_init
if self._read_config(config_file):
File "udocker", line 298, in _read_config
data = cfile.getdata()
File "udocker", line 911, in getdata
buf = filep.read()
OSError: [Errno 14] Bad address

```

I'm having trouble interpreting it, does this look familiar to anyone?

**Comment by skilbjo** [comment]
I noticed `udocker help` and `udocker --help` also generate the same error so seems likely there is a step I'm missing on setup; any ideas?

**Comment by jorge-lip** [comment]
Please try to remove all your exports, keep only UDOCKER_DIR
export UDOCKER_DIR=/tmp

**Comment by gmolto** [comment]
Hi, @skilbjo. If you are looking for an easy use of udocker in AWS Lambda, please consider taking a look at SCAR: https://github.com/grycap/scar

Regards,
Germán.

**Comment by skilbjo** [comment]
Thanks for the help @jorge-lip and @gmolto  !!!!

I was actually able to get it working. Well, almost- I still need to be able to run the container I download, seems like I need to also get the udocker-1.1.0-RC2.tar.gz from https://github.com/grycap/scar/tree/master/lambda. The current issue I have is

```
export UDOCKER_DIR=/tmp

cd /tmp

curl https://raw.githubusercontent.com/grycap/scar/master/lambda/udocker >/tmp/udocker
chmod +x udocker

udocker pull quay.io/skilbjo/iris:x86
udocker create --name=iris quay.io/skilbjo/iris:x86
udocker setup --execmode=F1 iris
udocker run --nosysdirs iris cat /etc/os-release

Error: no libfakechroot found for this host os
```

It seems the current `indigo-dc/udocker/master` and `indigo-dc/udocker/devel` branches are not working with AWS Lambda at the moment (the failure, always with the stack trace I posted above). The way I *was* able to get it working was with this command:

```
curl https://raw.githubusercontent.com/grycap/scar/master/lambda/udocker >/tmp/bin/udocker
```

`udocker` not working on AWS Lambda might not be an issue for you guys though, if so feel free to close/resolve this issue. 

I will post a working script (in comparison with the original script I opened the issue with) however once I get it working. It may help any newcomers who saw the blog post on HackerNoon but was not able to get it working (since that blog post is now out of date).

**Comment by skilbjo** [comment]
@jorge-lip and @gmolto might you have any idea what this `Error: patchelf executable not found` error means?

I seem to be making it quite far with this script, except for this particular error:

```
Warning: running as uid 0 is not supported by this engine
Warning: non-existing user will be created
Error: patchelf executable not found
```

here is my script
```
export UDOCKER_DIR=/tmp
export UDOCKER_BIN=/tmp/bin
export UDOCKER_LIB=/tmp/udocker_dir/lib

cd /tmp

# binary download from https://raw.githubusercontent.com/grycap/scar/master/lambda/udocker
ln -s /var/task/udocker /tmp/bin/udocker || :

# binary download from https://github.com/grycap/scar/blob/master/lambda/udocker-1.1.0-RC2.tar.gz
tar --directory='/tmp' -xf /var/task/udocker-1.1.0-RC2.tar.gz

udocker install

udocker pull busybox # quay.io/skilbjo/iris:x86
udocker create --name=iris busybox # quay.io/skilbjo/iris:x86
udocker setup --execmode=F1 iris

udocker run -v /dev -v /proc -v /etc/hosts --nosysdirs \
  iris ls /etc
```

**Comment by skilbjo** [comment]
Just a quick message. So it looks like it can work without issue (no `patchelf` error) with the `grycap/cowsay` image referred to in the example in https://github.com/grycap/scar. I noticed that `grycap/cowsay` is based on ubuntu:16.04 rather than busybox/alpine linux.

This may be an issue related to the problems with busybox alluded to in @gmolto 's excellent write up here: https://github.com/indigo-dc/udocker/issues/76 and https://github.com/grycap/scar/issues/28

However !! 

I also noticed this bit of code 

(from https://github.com/grycap/scar/blob/master/lambda/udocker )
```
    def select_patchelf(self):
        """Set patchelf executable"""
        conf = Config()
        arch = conf.arch()
        if arch == "amd64":
            image_list = ["patchelf-x86_64", "patchelf"]
        elif arch == "i386":
            image_list = ["patchelf-x86", "patchelf"]
        elif arch == "arm64":
            image_list = ["patchelf-arm64", "patchelf"]
        elif arch == "arm":
            image_list = ["patchelf-arm", "patchelf"]
```

which calls

(from https://github.com/grycap/scar/blob/master/lambda/udocker#L1134 )
```
    def arch(self):
        """Get the host system architecture"""
        arch = ""
        try:
            machine = platform.machine()
            bits = platform.architecture()[0]
            if machine == "x86_64":
                if bits == "32bit":
                    arch = "i386"
                else:
                    arch = "amd64"
            elif machine in ("i386", "i486", "i586", "i686"):
                arch = "i386"
            elif machine.startswith("arm"):
                if bits == "32bit":
                    arch = "arm"
                else:
                    arch = "arm64"
```

somehow, that is not returning `amd64`, for which surely the AWS machines running lambda are. 

for reference, `$(uname -a)` in AWS Lambda returns this
```Linux ip-10-34-75-211 4.9.81-35.56.amzn1.x86_64 #1 SMP Fri Feb 16 00:18:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

So at least the `patchelf` error could be resolved by modifying the `udocker` code to force-jam the lambda machines to return `amd64` when run on lambda.

**Comment by skilbjo** [comment]
Considering I was able to get this to work with ubuntu, and there is already an open issue related to Alpine Linux, I'm gonna close this. 

Also, I'm gonna take a look at using https://github.com/bitnami/minideb as an alternative base image that will probably work with udocker + AWS Lambda

**Comment by skilbjo** [comment]
Also, I was actually able to get past the patchelf error on the busybox/alpine image by just changing my dockerfile slightly: https://github.com/skilbjo/iris/blob/master/deploy/default/Dockerfile.arm

```
FROM resin/armhf-alpine:3.5

ENV QEMU_EXECVE=1

COPY deploy/qemu/qemu-arm-static /usr/bin/

RUN ["qemu-arm-static","/sbin/apk","-U","add","patchelf"]
```

**Comment by skilbjo** [comment]
But alas, I am now getting the `Error: command not found or has no execute bit set: ['usr/local/deploy/bin/run-job']` error referred to in the issues linked to this ticket; so I'd recommend minideb as an alternative to alpine linux

**Comment by alpegon** [comment]
Hi @skilbjo, we had the same issues when running alpine images.
Minideb is a good option to make small images, but if you want to go one step further you can check this project: https://github.com/grycap/minicon.
It allows to reduce even more the container image by removing all the libraries not used by the process inside the container.
Also, in the following weeks this functionality and more are going to be included in the scar framework: https://github.com/grycap/scar
