### ISSUE TITLE
Cannot install udcker, some links are broken

### ISSUE THREAD

**Issue by psafont** [indigo-dc/udocker#123]
I'm trying to install udocker with `udocker install`, but there are errors downloading from the URLs

The first one is 404, the two others don't seem to be valid .gz files and are different sizes from one another.

I'm using the udocker.py from the git tag v1.1.1

```
Info: installing 1.1.1
Info: installing from: http://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/tgz/udocker-1.1.1.tar.gz
Error: in download:
Info: installing from: https://cernbox.cern.ch/index.php/s/VC7GuVWA7mYRAiy/download
Error: in download:
Info: installing from: https://owncloud.indigo-datacloud.eu/index.php/s/AFImjw8ii0X72xf/download
Error: in download:
Error: installing tarball: https://owncloud.indigo-datacloud.eu/index.php/s/AFImjw8ii0X72xf/download https://cernbox.cern.ch/index.php/s/VC7GuVWA7mYRAiy/download http://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/tgz/udocker-1.1.1.tar.gz
Error: install of udockertools failed
```

**Comment by mariojmdavid** [comment]
I just did udocker install with no problems, may have been spurious
the cernbox.cern.ch and owncloud.indigo-datacloud.eu are ok
can you put the url in your browser to check?

**Comment by psafont** [comment]
One of the links is still broken (tried firefox, curl and httpie):
```
$ http http://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/tgz/udocker-1.1.1.tar.gz
HTTP/1.1 404 Not Found
Content-Length: 345
Content-Type: text/html
Date: Thu, 15 Mar 2018 09:18:05 GMT
Server: lighttpd/1.4.41

<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

**Comment by mariojmdavid** [comment]
hi, the other locations where added to solve these type of problems, i.e. if any location is broken, some of the others should work
nonetheless we will fix (upload) the tarball to repo.indigo

**Comment by psafont** [comment]
Thanks, I'm debugging to see what else is stopping the installation from happening.

**Comment by psafont** [comment]
It was an issue of mine. `UDOCKER_TMP` was pointing to a non-existing folder
