### ISSUE TITLE
Docker Attach udocker alternative

### ISSUE THREAD

**Issue by LucasSilvaFerreira** [indigo-dc/udocker#127]
Hi,
Is there some attach option to access a container after exit ?

**Comment by mariojmdavid** [comment]
when you exit the container you are not removing it, so just do
udocker run <CONTAINER_ID | CONTAINER_NAME> /bin/bash
and you are again inside the container

the container itself can be directly accessed in
.udocker/containers/<CONTAINER_ID>/ROOT/

tell us if you need further help

**Comment by LucasSilvaFerreira** [comment]
Hi Mario,
it worked pretty!
Thank you

**Comment by mariojmdavid** [comment]
no problem, will close the issue
