### ISSUE TITLE
Execution Difference between docker and udocker

### ISSUE THREAD

**Issue by tjhendrickson** [indigo-dc/udocker#130]
Hello,

I've a developed an image with docker and pushed it docker hub so it can be distributed. This image does some processing and runs perfectly fine on my local machine. For whatever reason when I try the same processing on the same data with udocker the container image fails and I receive an error message which reads: PROT_EXEC|PROT_WRITE failed.

I thought that it may perhaps have to do with the type of engine that udocker is using so I changed it to each one without success.

What is going on here?

**Comment by jorge-lip** [comment]
Need more information. Please specify:
- type of host, operating system distribution and version 
- container operating system and version
- does this happen only with this image ? or with any image ?
- can we download the image so that we can reproduce the problem ?

**Comment by tjhendrickson** [comment]
I'm going to close this issue. I discovered that the udocker execution had to be different in order so the container would run.
