### ISSUE TITLE
Can not add ssh-add key to ssh-agent inside docker-image

### ISSUE THREAD

**Issue by andersla** [indigo-dc/udocker#135]
I can not ssh-add testkey to a ssh-agent running inside a docker container that is being run via udocker.
(I would like to ssh to another computer from within docker-container and have ssh-key handled by ssh-agent within the image)
My host computer-OS is Ubuntu 16.04.

Here is my test-case that is failing:

```
udocker run --rm ubuntu:16.04 bash
apt-get update
apt-get install ssh

ssh-keygen testkey

eval "$(ssh-agent -s)"
ssh-add testkey

- This ssh-add command fails with: 
Could not add identity "testkey": communication with agent failed
```

my udocker version:
version: 1.1.1
tarball: https://owncloud.indigo-datacloud.eu/index.php/s/AFImjw8ii0X72xf/download https://cernbox.cern.ch/index.php/s/VC7GuVWA7mYRAiy/download http://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/tgz/udocker-1.1.1.tar.gz

```

**Comment by jorge-lip** [comment]
This seems to be an upstream issue in proot the default engine used by udocker.
Can try two things.
1) use: udocker run -v /tmp  --rm  ubuntu:16.04  bash
or
2) try an alternative execution mode:

# INSTALL MUST BE DONE WITH THE DEFAULT MODE (P1)
$ udocker create  --name=ub16  ubuntu:16.04
$ udocker run ub16  bash
apt-get update
apt-get install ssh
ssh-keygen testkey

# ONCE INSTALLED CHANGE TO MODE F3
$ udocker  setup  --execmode=F3   ub16
$ udocker run  -v /tmp  ub16
eval "$(ssh-agent -s -a myagent)"
ssh-add  testkey

you need to kill the ssh-agent upon exit.

**Comment by andersla** [comment]
I didnt get no 1 to work, but no 2 did. Thanks
