### ISSUE TITLE
Mac OSX

### ISSUE THREAD

**Issue by aunderwo** [indigo-dc/udocker#136]
Does this tool work on Mac OSX?

I'm getting an error

./udocker create --name=verybusy busybox
Error: while extracting image layer
Error: while extracting image layer
Error: creating container: 786f73c3-880e-33c0-964a-802387de4730
786f73c3-880e-33c0-964a-802387de4730

**Comment by jorge-lip** [comment]
Sorry but the only host OS supported is Linux. On MacOS you need to run it on a VM with Linux as container technologies always rely on a Linux kernel.
