### ISSUE TITLE
It seems to be sharing network with other containers when not

### ISSUE THREAD

**Issue by jimonreal** [indigo-dc/udocker#151]
I am running 6 containers in parallel using udocker.
Each of them connect to a localhost:staticPort.
It only works for one, the other 5 say they can not bind, port already being used.

What could be the problem?
Do I need to pass some extra parameters? like --novol some directory?

Bests

**Comment by mr-c** [comment]
Hello @jimonreal , the networking features of Docker are not a part of `udocker`; You'll need to manually adjust your applications to not use the same ports.

**Comment by jimonreal** [comment]
Hello @mr-c , does that mean that an instance of an udocker container is not really a container?
The ports used inside a container, are also used outside of it? or shared along with other containers?

**Comment by mr-c** [comment]
It is a container mimic, but not a real container. You can read more about it at https://doi.org/10.1016/j.cpc.2018.05.021

**Comment by jimonreal** [comment]
@mr-c Thanks! That clarification helped me a ton. Now I am able to use udocker "containers" how they are supposed, and making the best out of it.
