### ISSUE TITLE
Split unit tests into multiple files?

### ISSUE THREAD

**Issue by yuvipanda** [indigo-dc/udocker#154]
Similar to #116, but for the unit and functional tests. Currently they're big single files, and it would be great if they'd be multiple smaller files. While udocker being a single file or pex seems an important requirement, I think the tests could easily be split up.

If the maintainers are ok with it, I'm happy to use this as an opportunity to contribute to the project :)

**Comment by jorge-lip** [comment]
Hi yuvipanda,
Sure contributions are welcome  :) 
That is something that has been postponed for lack of time.

**Comment by mariojmdavid** [comment]
work ongoing in branch devel3, largely done
