### ISSUE TITLE
error building from source

### ISSUE THREAD

**Issue by rgiannico** [indigo-dc/udocker#157]
Hello,
I tried building from source but I get this error using build_tarball.sh
It seems like realpath is a "not so standard" command, at least for my CentOS 6.1 
It's not a big deal (I can install using the udocker.py) but I still think this should be fixed :)

```
$ git clone https://github.com/indigo-dc/udocker
$ cd udocker/utils
$ bash build_tarball.sh
build_tarball.sh: line 1118: realpath: command not found
dirname: missing operand
Try `dirname --help' for more information.
dirname: missing operand
Try `dirname --help' for more information.
sanity_check
/udocker.py not found aborting
```

**Comment by jorge-lip** [comment]
Fixed in the devel branch.

**Comment by jorge-lip** [comment]
Added to 1.1.2
