### ISSUE TITLE
what is neccessary for udocker to work under WSL (win 10) ?

### ISSUE THREAD

**Issue by katakombi** [indigo-dc/udocker#159]
I've tried udocker under WSL in Win 10 Pro and it fails on creation of the container.
Since docker is working it should be somehow possible to make udocker running, too. Am I right?
What are the burdens?

I can occasionally reproduce the detailed python error trace later if it is helpful. So far I just remember that udocker died because it failed to find a PID of a process its trying to stop.

**Comment by jorge-lip** [comment]
We don't have windows to try this, but if someone does and is willing to do the fixes would be great.
WSL does not use a Linux kernel, instead it emulates the Linux kernel interfaces. 
Notice that the implementation of PTRACE in WSL has many limitations and the Pn execution modes will likely not work.

**Comment by katakombi** [comment]
This is what I obtain in ubuntu 18.04 under WSL. Maybe just a missing python dependency or a wrong tar version?

```
katakombi@DESKTOP-8R6NPH3:~$ ./udocker create --name=test bash
Traceback (most recent call last):
  File "./udocker", line 7102, in <module>
    sys.exit(Main().start())
  File "./udocker", line 7090, in start
    exit_status = self.execute()
  File "./udocker", line 7073, in execute
    status = cmds[command](self.cmdp)     # executes the command
  File "./udocker", line 6240, in do_create
    container_id = self._create(imagespec)
  File "./udocker", line 6259, in _create
    imagerepo, tag)
  File "./udocker", line 3739, in create_fromimage
    status = self._untar_layers(layer_files, container_dir + "/ROOT")
  File "./udocker", line 3826, in _untar_layers
    self._apply_whiteouts(tarf, destdir)
  File "./udocker", line 3811, in _apply_whiteouts
    proc.terminate()
  File "/usr/lib/python2.7/subprocess.py", line 1274, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python2.7/subprocess.py", line 1269, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
```

**Comment by katakombi** [comment]
Update:
The layer untarring runs into an unhandled exception. If I catch the exception (OSError: [Errno 3]: No such process) the container creation works. Then I can set the execmode to F4. 
```
udocker pull alpine
udocker create --name=a alpine
```
But then I fail when entering the container:
```
TODO
```
Under Linux it succeeds like this:
```
udocker run --user=$(whoami) a sh -c 'hostname'
Warning: non-existing user will be created
 ############################################################################## 
 #                                                                            # 
 #               STARTING 339c1ab3-8cf7-3d0b-a5b8-6f30edf3070a                # 
 #                                                                            # 
 ############################################################################## 
 executing: sh
khaleesi

```

**Comment by katakombi** [comment]
Note I've tried exec modes P1 P2 F1 F2 F3 F4 R1 but none of them worked. I've assumed F4 would be the best start to with...

**Comment by katakombi** [comment]
Okay I've reinstalled ubuntu 18.04 and the alpine container works in F1 mode now!

**Comment by umrashrf** [comment]
🥇

**Comment by joaompinto** [comment]
WSL2 provides a "regular" kernel implementation using a VM. I have tested udocker on it with success.

Please note that WSL2 is not generally available yet, it requires the insider preview:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by katakombi** [comment]
> WSL2 provides a "regular" kernel implementation using a VM. I have tested udocker on it with success.
> 
> Please note that WSL2 is not generally available yet, it requires the insider preview:
> https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

Thanks for the info, I was hoping that WSL2 would solve that issue entirely :) Now I am assured...
