### ISSUE TITLE
Failing download in python and 'ls' command in Fakechroot execmode

### ISSUE THREAD

**Issue by vykozlov** [indigo-dc/udocker#160]
udocker version: devel branch as of 24.09.2018

Two problems when --execmode=F1 / F2 / F3 is used:

1.) Can't download remote files from a python script:
from six.moves import urllib
urllib.request.urlretrieve(remoteURL, ...)

the script fails with
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) 

while it works with curl via:
$ curl -L -o filename https://remoteURL

2.) if a host directory mounted in the container (via --volume hostDir:containerDir), it is not possible to list files in the directory while being inside the container:

ls: cannot open directory '.': No such file or directory 

Both problems do not exist in --execmode=P1 / P2

**Comment by jorge-lip** [comment]
@vykozlov could you try these two issues against the latest 1.1.3 release.
If the container is already in Fn mode then you will need to setup again with --force

udocker  setup  --execmode=Fn  --force  container

**Comment by jorge-lip** [comment]
udocker [1.1.4](https://github.com/indigo-dc/udocker/tree/v1.1.4) has been released.
if problems persists please reopen or create a new issue.
