### ISSUE TITLE
Udocker hanging and default location of docker containers

### ISSUE THREAD

**Issue by jlevy44** [indigo-dc/udocker#175]
I'm running udocker as nonroot on an hpc system.

Tried to run nohup udocker create --name=xxx [docker_user]/xxx:[tag] && udocker setup --execmode=F3  xxx & && udocker run xxx

And command just hung. I was notified by the HPC admins that I had exceeded my disk space. However, I have an alternative disk space that has more storage. How do I create my containers over there? Why does it take so long to load vs docker?

Also have been trying to run toil with udocker. Running into the same problems.

**Comment by jorge-lip** [comment]
If you want to place the created containers in a different directory you can use the environment variable UDOCKER_CONTAINERS. If you want to place everything (downloaded images, containers, tools etc) in a different place then use the environment variable UDOCKER_DIR. 
udocker does everything without privileges as such cannot mount the images as docker does and therefore needs to extract the tarballs into some directory which is much slower. The F3 mode also needs to make changes to every executable, shared library and symbolic link in the container.
If you pulled an image, created the container you may delete the pulled image to save space.
Also notice that once created (with udocker create) you can run the container as many times as you need and that should be fast.

**Comment by jlevy44** [comment]
Thanks!
