### ISSUE TITLE
Sporatic missing file pointers

### ISSUE THREAD

**Issue by DavidAustinNix** [indigo-dc/udocker#176]
Hello Folks!

I'm using udocker (1.1.3) on a slurm cluster to run snakemake workflows to process genomic sequencing data. Each job run is ~12-24hrs.  With a small number of jobs, I find no issues but with ~10 or more I'm seeing ~1/2 the jobs fail due to missing file exceptions.  Yet the files are there. Its as if the "mounted" drives in the udocker container disappear.  

They fail at different times with different missing files.  I can't get a single job to fail.  Its only when under heavy IO load with many simultaneous jobs all using the same shared udocker built container that problems occur.  Switching execution modes from P1 to P2 didn't help.

Any Suggestions? 

Thanks,
David, Huntsman Cancer Institute

**Comment by mariojmdavid** [comment]
hi @DavidAustinNix 
P modes impact quite a lot on heavy I/O, can you try/test with the F mode. 
check first if you can have the files/dir in the container as you have now

**Comment by DavidAustinNix** [comment]
I was able to get F4 to partially run.  It works with some applications but not with all in the docker container.  I'm seeing a lot of C library issues with these apps that kill the job.  The other Fs don't support the installed java in the container.  Any other suggestions?

**Comment by jorge-lip** [comment]
Is the container public and can you point us to ways to test it ?

**Comment by DavidAustinNix** [comment]
Yes it is public, take a look at the readme in https://github.com/HuntsmanCancerInstitute/Workflows/tree/master/Hg38RunnerWorkflows/SomExoCaller 

The problem is that to test it you'd need to download the ~250GB data bundle and ~100GB of bam alignment files.

**Comment by DavidAustinNix** [comment]
Hello Folks, I switch the problematic workflows to Singular and stress tested it. No issues so the problem is with the default execution engine in udocker.  Good luck, its a troublesome issue to debug.
