### ISSUE TITLE
udocker and MPICH

### ISSUE THREAD

**Issue by alahiff** [indigo-dc/udocker#179]
It's quite easy to get udocker working with OpenMPI, however I'm having trouble with MPICH: I always get errors like this:
```
[cli_0]: write_line error; fd=6 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : Bad file descriptor
[cli_0]: Unable to write to PMI_fd
[cli_0]: write_line error; fd=6 buf=:cmd=get_appnum
:
system msg for write_line failure : Bad file descriptor
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474):
MPID_Init(152).......: channel initialization failed
MPID_Init(426).......: PMI_Get_appnum returned -1
[cli_0]: write_line error; fd=6 buf=:cmd=abort exitcode=1094159
:
system msg for write_line failure : Bad file descriptor
```
I've tried a variety of execution modes but that doesn't help. Has anyone else experienced this?

For reference, Singularity used to have a similar problem, see e.g. https://github.com/sylabs/singularity/issues/1571, which has been resolved.

**Comment by jorge-lip** [comment]
Can you try with version 1.3.5
https://github.com/indigo-dc/udocker/releases/tag/1.3.5

**Comment by jorge-lip** [comment]
This issue is too old. If problem persists please reopen.
