### ISSUE TITLE
Issue with kernel with non-integer in the name

### ISSUE THREAD

**Issue by dsobral** [indigo-dc/udocker#183]
Hello, 

I tried udocker in a server with slackware 14.0 and the kernel has non-integers in the name:
> uname .r
3.2.31.c

This creates an error in the kernel verification step.
If I manually skip that step it then works.

Daniel

**Comment by mariojmdavid** [comment]
Jorge can fix this, but why people keep inventing things, instead of keeping to reasonable and sensible
https://semver.org/

**Comment by dsobral** [comment]
It's not a serious issue, just thought of letting you know of this case.

**Comment by jorge-lip** [comment]
Fixed in the the latest production release [1.1.4](https://github.com/indigo-dc/udocker/tree/v1.1.4).
Thanks !
