### ISSUE TITLE
Modularize into udocker/runU

### ISSUE THREAD

**Issue by nponeccop** [indigo-dc/udocker#190]
Upstream docker seem to use `runc` now, so the work is split:

- runc only runs OCI bundles
- docker does everything else (such as fetching from registry, providing `ps` commands and so on)

So if you implement runU, it could be ran by those running pure runC now (runC is perfectly usable w/o docker, and bundle format is standardized).

**Comment by jorge-lip** [comment]
udocker Rn modes already use runC. The latest version of udocker in the devel branch can load OCI containers as well.

**Comment by nponeccop** [comment]
JFYI there is a reportedly modular Docker clone from IBM/RedHat named `podman` so taking some ideas/code from it might be useful for `udocker`
