### ISSUE TITLE
Error: command not found or has no execute bit set:  [u'/hello']

### ISSUE THREAD

**Issue by brianjimenez** [indigo-dc/udocker#196]
Just downloaded and installed the latest release udocker-1.1.3.tar.gz in macOS:

```
tar zxvf udocker-1.1.3.tar.gz
cd udocker-1.1.3/
./udocker install
./udocker run hello-world
Downloading layer: sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Error: while extracting image layer
Error: while extracting image layer
Error: creating container: 866ed27f-60f4-3548-8fc6-0d3df659dbbf
Warning: non-existing user will be created
Error: command not found or has no execute bit set:  [u'/hello']
```

Checking permissions, all seems to be OK:

```
ls -la
lrwxr-xr-x@  1 bjimenez  staff    10B Nov  1  2018 udocker -> udocker.py
-rwxr-xr-x   1 bjimenez  staff   279K May  8 08:28 udocker.py
```

Any clue? Thanks in advance for your time.

**Comment by jorge-lip** [comment]
Currently udocker is not supported on MacOS.

**Comment by brianjimenez** [comment]
Thanks for the quick response! Is there any plan to make it supported on macOS or there is any unachievable technical requirement?

**Comment by katakombi** [comment]
see this https://github.com/proot-me/proot/issues/155
and this https://github.com/proot-me/proot/issues/155

I can't speak for croot, but singularity has no plans AFAIK for OSX

**Comment by jorge-lip** [comment]
As mentioned by @katakombi  this will be only possibly if there are stable upstream tools that we can integrate in udocker to do it. There is for instance [Noah](https://github.com/linux-noah/noah/blob/master/man/noah.md) but I haven't had time nor a machine to do it ;)

**Comment by katakombi** [comment]
FYI there's something changing on the singularity front: Sylabs offers now a commercial cut-down version of singularity for MacOSX.

**Comment by jorge-lip** [comment]
This issue is too old.
