### ISSUE TITLE
can i use my prebuild docker images with udocker on cluster and laptop,?

### ISSUE THREAD

**Issue by naveen584** [indigo-dc/udocker#199]
can i use my prebuild docker images with udocker on cluster and laptop,  if yes then how??

**Comment by mariojmdavid** [comment]
hi, yes
example of docker centos:7 image

if in dockerhub, directly with udocker

udocker pull centos:7

if in your laptop
docker save centos:7 > centos
udocker load -i centos

**Comment by nponeccop** [comment]
See https://github.com/indigo-dc/udocker/blob/master/README.md

Basically you can  `export` or `save` your image from docker, or `push` it to a registry.

Udocker can work with exported and saved images, and pull directly from docker registries, including private ones.

**Comment by naveen584** [comment]
ok ,  another doubt  is, is that mandatory to have docker image on  docker hub, suppose if i have stored my images on private registry then how i can use udocker??
