### ISSUE TITLE
Unable to use export to stdin

### ISSUE THREAD

**Issue by joaompinto** [indigo-dc/udocker#202]
According to the help, udocker export - should allow me to export the to a stream, instead it's report a syntax error:

> 10:06 $ udocker export - $CID 
> Error: creating tar file: -
> Error: exporting container file system: 68fbcfb2-707e-37d3-884a-48df15368cd7
> Error: syntax error at: -
>

**Comment by jorge-lip** [comment]
can you please test with a pipe such as ?

udocker export - $CID | tar tvf -

**Comment by joaompinto** [comment]
@jorge-lip it does work, so the bug is only resulting in  the error / exit code. Thanks

**Comment by jorge-lip** [comment]
Return code fixed in [1.1.4](https://github.com/indigo-dc/udocker/tree/v1.1.4). Closing this ticket.
