### ISSUE TITLE
add to setup.py: long_description_content_type="text/markdown", 

### ISSUE THREAD

**Issue by mariojmdavid** [indigo-dc/udocker#211]
this is needed to render markdown into pypi with newer versions of twine
...
setup(
    author="Jorge Gomes",
    author_email='udocker@lip.pt',
    version="1.1.3-1",
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Intended Audience :: End Users/Desktop',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: Apache Software License',
        'Natural Language :: English',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
    ],
    description="A basic user tool to execute simple docker \
        containers in batch or interactive systems without root privileges",
    scripts=['udocker'],
    install_requires=requirements,
    license="Apache Software License 2.0",
    long_description=readme + '\n\n' + history,
    long_description_content_type="text/markdown",
^^^^^^^

**Comment by jorge-lip** [comment]
Added to devel branch
