### ISSUE TITLE
Add flag --env-file <file>

### ISSUE THREAD

**Issue by dsalomoni** [indigo-dc/udocker#212]
Docker has the flag --env-file <file> (https://docs.docker.com/engine/reference/commandline/run/) to pass multiple environment variables at once. Currently, udocker only supports --env="MYTAG=xxx". It would be useful to introduce --env-file <file> in udocker as well.

**Comment by jorge-lip** [comment]
Added to the latest production release [1.1.4](https://github.com/indigo-dc/udocker/tree/v1.1.4).
Closing this ticket, please open a new issue if you problems with this feature.
