### ISSUE TITLE
udocker in docker

### ISSUE THREAD

**Issue by zaoqi** [indigo-dc/udocker#216]
```][root@650de1c5b41b /]# export PROOT_NO_SECCOMP=1
[root@650de1c5b41b /]# ./udocker --allow-root run hello-world
Warning: check container content: 04b55606-52f1-30f9-8881-9061ed59b528
Warning: non-existing user will be created
 
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING 04b55606-52f1-30f9-8881-9061ed59b528                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: hello
proot error: ptrace(TRACEME): Operation not permitted
proot error: execve("/hello"): Operation not permitted
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot-x86_64-4_8_0 --help`.
proot error: can't chmod '/tmp/proot-369-I5QAH9': No such file or directory
```

**Comment by mariojmdavid** [comment]
if you want to run udocker inside a docker container you should set the --execmode= to one of the Fxx
the P(root) modes don't work, or don't work properly
can you try the following:

$ docker run -it ubuntu:18.04 /bin/bash

inside the docker container
apt update
apt -y upgrade
apt install curl
apt -y install python
curl https://raw.githubusercontent.com/indigo-dc/udocker/master/udocker.py > udocker
 chmod u+rx ./udocker
./udocker --allow-root install
./udocker --allow-root pull centos
./udocker --allow-root create
./udocker --allow-root  create --name=c7 centos
./udocker --allow-root  setup --execmode=F1 c7
./udocker --allow-root  run c7

now inside the udocker container
cat /etc/os-release

**Comment by jorge-lip** [comment]
The Linux PTRACE does not work inside docker that's why Pn modes fail.
You can disable seccomp in docker but also consider the implications if do not trust the container.

docker  run  -i  -t  --security-opt  seccomp=unconfined  centos:centos7

Or as stated above use the Fn modes.
