### ISSUE TITLE
How to Change execution engine mode for all containers?

### ISSUE THREAD

**Issue by zaoqi** [indigo-dc/udocker#217]

**Comment by katakombi** [comment]
You'd need to patch udocker.py if you wanted udocker to use a different engine as default. There is no setting as far as I know.
Otherwise you could write a simple bash script to loop over all containers and change the mode for each of them. Something like (pseudocode):
```
for container in $(udocker ps | awk '{print $onlyContainerUUIDs}' ; do udocker setup --container-mode=YourMode $container; done
```

**Comment by jorge-lip** [comment]
We do not provide a way to change the default execution engine. You can use the solution proposed by katakombi above or use the latest production release [1.1.4](https://github.com/indigo-dc/udocker/tree/v1.1.4) which supports the new environment variable UDOCKER_DEFAULT_EXECUTION_MODE, this allows to select the default execution mode.
However modes such as F2, F3 and F4 cannot be supported as default modes.

`UDOCKER_DEFAULT_EXECUTION_MODE=F1 ./udocker run CONTAINER-ID`
