### ISSUE TITLE
download.ncg.ingrid.pt no longer has a valid SSL certificate

### ISSUE THREAD

**Issue by mr-c** [indigo-dc/udocker#221]
Perhaps it should be removed from https://github.com/indigo-dc/udocker/blob/master/doc/installation_manual.md ?

Happy to send a pull request to do so, if that would be accepted.

**Comment by mr-c** [comment]
https://www.sslshopper.com/ssl-checker.html#hostname=download.ncg.ingrid.pt

> The certificate is not trusted in all web browsers.

>  None  of the common names in the certificate match the name that was entered  (download.ncg.ingrid.pt). You may receive an error when accessing this  site in a web browser.

> Common name: download.novalocal
Organization: SomeOrganization Org. Unit: SomeOrganizationalUnit
Location: SomeCity, SomeState, --
Valid from August 27, 2019 to August 26, 2020
Serial Number: 4500 (0x1194)
Signature Algorithm: sha256WithRSAEncryption
Issuer: download.novalocal

**Comment by mariojmdavid** [comment]
httpd certificate misconfigured
now solved
