### ISSUE TITLE
How suppress the container execution prolog

### ISSUE THREAD

**Issue by pditommaso** [indigo-dc/udocker#23]
Is there a way to suppress the prolog printed in the stdout when a container is executed? 

I mean the text: 

```
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING 9e08bb88-4548-3081-a265-310b83be43f0                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: sh
```

**Comment by jorge-lip** [comment]
Currently there isn't.
We can provide this feature in the next release.

**Comment by pditommaso** [comment]
Thanks. A possible alternative would be to print it on the `stderr` channel so that it would not *break* the output that may be expected by the containerised tools.
