### ISSUE TITLE
login harbor Registry

### ISSUE THREAD

**Issue by lidanqing123** [indigo-dc/udocker#230]
Can  udocker login harbor Registry?  i tried, but it dosen't work. I wonder if there is something wrong with my configuration.

**Comment by jorge-lip** [comment]
Not tested but you can try the development version that some fixes in the authentication and pulling.
`curl https://raw.githubusercontent.com/indigo-dc/udocker/devel/udocker.py > udocker`

**Comment by jorge-lip** [comment]
The latest production release [1.1.4](https://github.com/indigo-dc/udocker/tree/v1.1.4) is available. We would appreciate feedback on whether it works.

**Comment by jorge-lip** [comment]
Fixes for login were introduced in v1.3.0.
