### ISSUE TITLE
symlinks in mounted volumes

### ISSUE THREAD

**Issue by sebastian-luna-valero** [indigo-dc/udocker#233]
Hi,

If I have on my host system:
```
/mydir
/mydir/symlink   # pointing to another folder on the same filesystem
```

and do:
```
udocker run --volume=/mydir:/workdir <container>
```

Inside the container I can:
```
# this works
ls /workdir
ls /workdir/symlink

# this fails: No such file or directory
ls /workdir/symlink/
```

Is this expected?

Best regards,
Sebastian

**Comment by jorge-lip** [comment]
Hi,
Depends on weather the symbolic link points to a file within the same directory tree or outside.
if symlink points to /mydir/AAA it should work
if symlink points to /AAA it should fail

**Comment by sebastian-luna-valero** [comment]
Make sense, thank you very much!
