### ISSUE TITLE
shipping bundled with singularity?

### ISSUE THREAD

**Issue by katakombi** [indigo-dc/udocker#236]
Hi,

 I've recently checked out the Go rewrite of singularity, created a static build and installed it locally (without SUID). If I point the $PATH to it I can use udockers S1 engine right-away.

Singularity offers many exciting features such as multiple image formats, signing, encryption and remote building. Also pulling from docker repos works fast and reliably. 

I would like to raise the question whether the limitations of the S1 engine which are applied in udocker could technically be smoothed out, i.e.
 - shipping with a statical build of singularity
 - S1 fakeroot support
 - S1 file bind support

Regarding fakeroot I can't see why this should not be doable. File binds could be implemented by creating non-existing bind targets beforehand inside the container, and remove them on termination.

When it comes to statical building with GO I don't know enough about it to tell whether the produced binary satisfies the requirements for shipping with udocker. 
I'll provide my build for anyone willing to play with it:
https://dolmades.org/mirror/singularity
https://sylabs.io/guides/3.4/user-guide/

Cheers Stefan

**Comment by katakombi** [comment]
https://github.com/sylabs/singularity/issues/4775

**Comment by jorge-lip** [comment]
Hi,
We plan to add fakeroot to the Fn modes will look into that for Sn.
Added a static build of Singularity will be great, before it was not possible.
I guess you want file bind as opposed to directory bind. This works in Pn and Fn modes because these modes work by rewriting pathnames, however singularity and similar can only bind directories.
Cheers Jorge

**Comment by katakombi** [comment]
> Hi,
> We plan to add fakeroot to the Fn modes will look into that for Sn.
> Added a static build of Singularity will be great, before it was not possible.
> I guess you want file bind as opposed to directory bind. This works in Pn and Fn modes because these modes work by rewriting pathnames, however singularity and similar can only bind directories.
> Cheers Jorge

Actually it is possible to bind files, too. Just with the restriction that the target must exist within the container env.

**Comment by jorge-lip** [comment]
Ok great will fix that.

**Comment by katakombi** [comment]
Just to add - there's a couple of reasons file binds are great
- overwrite /etc/users /etc/group
- bind devices under /dev
- binding ~/.Xauthority for having X11 support
