### ISSUE TITLE
udocker tarball installation questionable

### ISSUE THREAD

**Issue by katakombi** [indigo-dc/udocker#237]
Hi,

 I've noticed that the udocker tarball installation behaves oddly:
1. There are two directories created ~/.udocker/{bin,lib} - both are identical. Guess that can be avoided.
2. Permissions in both aforementioned dirs prevent the subsequent removal `rm -rf ~/.udocker`. 

This is new in `devel` branch.

**Comment by jorge-lip** [comment]
Hi,
Please try with the latest version in devel.

**Comment by katakombi** [comment]
I confirm 1. and 2. as solved!
Thanks for fixing :) Looking fwd to upcoming 1.1.4 is there a estimated deadline?

**Comment by jorge-lip** [comment]
Thanks for the feedback. Possibly in the beginning of the year.
