### ISSUE TITLE
can't run as root

### ISSUE THREAD

**Issue by Taylor95** [indigo-dc/udocker#242]
I'm trying to pull images but can't run as root and even change the workdir. I tried several images and all got the same erro 

> 
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING 125a4294-84e5-3907-a672-d1dc0633aa4f                * 
 *                                                                            * 
 ****************************************************************************** 

> executing: bash
125a4294# ls
R  miniconda2  perl5  temp
125a4294# cd ~
125a4294# ls
R  miniconda2  perl5  temp
125a4294# cd ./Public 
125a4294# ls
R  miniconda2  perl5  temp
125a4294# cd /Public/taylor
125a4294# ls
R  miniconda2  perl5  temp
125a4294# exit

**Comment by jorge-lip** [comment]
Can you provide more details, such as 
- version of udocker that you are using
- the command line use to invoke udocker
- the container image if publicly available 
- the Linux distribution in the host
- the filesystem type in the host

You can also try to change the execution mode to F3 before running and see if it helps:
udocker setup --execmode=F3 <container-id>

**Comment by Taylor95** [comment]
I am using udocker1.1.3

>[taylor@localhost dt3]$ cat /proc/version
Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018
[taylor@localhost dt3]$ udocker pull ubuntu
Downloading layer: sha256:7ddbc47eeb70dc7f08e410a6667948b87ff3883024eb41478b44ef9a81bf400c
Downloading layer: sha256:c1bbdc448b7263673926b8fe2e88491e5083a8b4b06ddfabf311f2fc5f27e2ff
Downloading layer: sha256:8c3b70e3904492c753652606df4726430426f42ea56e06ea924d6fea7ae162a1
Downloading layer: sha256:45d437916d5781043432f2d72608049dcf74ddbd27daa01a25fa63c8f1b9adc4
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
[taylor@localhost dt3]$ udocker create --name=L_ubuntu ubuntu
49f19d91-caa1-35e8-b3b6-da963fc258c9
[taylor@localhost dt3]$ udocker run -v /Public/:/Public/ L_ubuntu /bin/bash
 
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING 49f19d91-caa1-35e8-b3b6-da963fc258c9                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: bash
49f19d91#

**Comment by jorge-lip** [comment]
In what type of file system is /Public and the home directory ? 
Some filesystems have problems with the default Pn modes. Did you try the Fn modes namely:
`udocker setup --execmode=F3`

Does this happen only with the mounted volumes or also within the container directories ?
If it happens only with mounted volumes and if the files are not big, you can copy them to the container directory. Use  `udocker inspect -p container-id`  to see where the container directory is.

You can also try the version in the development branch see: 
https://github.com/indigo-dc/udocker/blob/master/doc/installation_manual.md

**Comment by Taylor95** [comment]
I tried `udocker setup --execmode=F3`. It can work now.
Thank you ver much!

**Comment by jorge-lip** [comment]
Closing.
