### ISSUE TITLE
`sudo` always missing

### ISSUE THREAD

**Issue by abmyii** [indigo-dc/udocker#253]
I've noticed that `sudo` is never present in any containers which causes problems for commands that require `sudo`. Right now I simply make a `/bin/sudo` file whenever I create a new container, which contains this:
```
"$@"
```
Could this be added, somehow?

Thank you for this awesome tool!

**Comment by fieu** [comment]
This is a Docker container specific issue if any. Off-topic.

**Comment by abmyii** [comment]
Ah, you are correct. Closing the issue.
