### ISSUE TITLE
does udocker work without access to the internet?

### ISSUE THREAD

**Issue by mrsewell** [indigo-dc/udocker#269]
I apologize for the question since I am a new user and not very computer literate. Does udocker require access to the internet to function? I can use udocker locally on my linux partition of my laptop and my directory (head node) of my institution's computer cluster. The reason I ask if udocker runs without internet access is that I can't get "udocker run" or even "udocker help" to run on the compute nodes/target/execute machines of our HPC. I know the compute nodes of our HPC do not have access to the internet. Having access or not to the internet is the only difference I am aware of between my directory on the head node and the compute nodes. Our system administrator is MIA and no one has been onsite since mid-March. I know the eventual plan is to give the compute nodes access to the internet (and reinitialize Docker- which had been turned off to perform an update several months ago). When I run udocker on a target/execute machine I get the following error:

Traceback (most recent call last):
  File "./udocker", line 8547, in <module>
    sys.exit(Main().start())
  File "./udocker", line 8486, in __init__
    self.udocker = Udocker(self.localrepo)
  File "./udocker", line 7095, in __init__
    self.dockerioapi = DockerIoAPI(localrepo)
  File "./udocker", line 5857, in __init__
    self.curl = GetURL()
  File "./udocker", line 5529, in __init__
    self._select_implementation()
  File "./udocker", line 5537, in _select_implementation
    elif GetURLexeCurl().is_available():
 File "./udocker", line 5726, in is_available
    return bool(FileUtil("curl").find_exec())
  File "./udocker", line 1336, in find_exec
    cmd = self._find_exec(["type", "-p", self.basename])
  File "./udocker", line 1322, in _find_exec
    exec_pathname = Uprocess().get_output(cmd_to_use)
  File "./udocker", line 410, in get_output
    close_fds=True)
  File "./udocker", line 400, in check_output
    return subprocess.check_output(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

Any help would be greatly appreciated. 
Thanks
Matt

**Comment by jorge-lip** [comment]
Hi,
It seems that the compute nodes do not have the pycurl module for python 2, then udocker tries to locate the `curl` executable using `type` but also fails. Check that the command `type` is in your path in the compute nodes and that it works. udocker uses which or type to locate other Linux commands. If this is fixed and the home is shared across the cluster it should work.

**Comment by mrsewell** [comment]
Thank you so much. Like I said I have pretty much no experience with python. I will fiddle around with your suggestions. I was also thinking about trying to run udocker in a virtualenv to see if that helps by giving me some more control over the python2 environment udocker run in (not sure if that is an actual viable solution).

**Comment by jorge-lip** [comment]
A virtual env can be an option to run udocker. Now there is also a version of udocker for Python 3. 
Obtaining the pathnames of the executables has also been improved on branches devel and devel3 for Python 2 and Python 3.
