### ISSUE TITLE
udocker unexpectedly uses P1 exec mode instead of P2 for kernel versions <= 4.8.0

### ISSUE THREAD

**Issue by jorsn** [indigo-dc/udocker#274]
Udocker unexpectedly uses P1 exec mode instead of P2 for kernel versions <= 4.8.0.
**Edit:** This apparently can be a problem for patched older kernels out of the user's control, e.g. in a shared webspace.
`udocker setup --help` indicates that P2 were always respected:

https://github.com/indigo-dc/udocker/blob/f448dfeb519158d9754ab08c6843523fb3ab3820/udocker.py#L8084

The corresponding lines (3205..3209) of [udocker.py, rev f448dfeb519158d9754ab08c6843523fb3ab3820 (current devel)](https://github.com/indigo-dc/udocker/blob/f448dfeb519158d9754ab08c6843523fb3ab3820/udocker.py) are:

```python
if HostInfo().oskernel_isgreater((4, 8, 0)):
            if conf.proot_noseccomp is not None:
                self.proot_noseccomp = conf.proot_noseccomp
            if self.exec_mode.get_mode() == "P2":
                self.proot_noseccomp = True
```

I think, the documentation is right, and the code wrong, isn't it?

**Comment by jorge-lip** [comment]
Fixed in 1.1.7
