### ISSUE TITLE
Error: while extracting image layer

### ISSUE THREAD

**Issue by bitcometz** [indigo-dc/udocker#275]
Hello,

I install the udocker package and run :
./udocker pull ncbi/pgap:2020-03-30.build4489

the URL: https://hub.docker.com/r/ncbi/pgap/tags

And then:
./udocker create --name=mypgap ncbi/pgap:2020-03-30.build4489
**Error: while extracting image layer**
**Error: while extracting image layer**

I try many times but it keeps reporting errors.

Could you help me with this problem?

Thanks!

**Comment by BorjaEst** [comment]
Same problem here.
When I create my image I get the following:
```sh
$ udocker create --name=o3skim synergyimk/o3skim
...
usr/local/lib/python3.8/xmlrpc/__pycache__/
usr/local/lib/python3.8/xmlrpc/__pycache__/__init__.cpython-38.pyc
usr/local/lib/python3.8/xmlrpc/__pycache__/client.cpython-38.pyc
Error: while extracting image layer
....
Error: creating container: 7ae5614b-2612-3c74-b2a5-e4968bace984
7ae5614b-2612-3c74-b2a5-e4968bace984
```
It might be a problem with __cpython__ (which I need in my application).

However, might be a OS dependent as for example:
 - In this machine __does NOT__ work:
```sh
$ uname --all
Linux _xm1x_ 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- In this machine __DOES__ work:
```sh
uname --all
Linux _xm2x_ 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jorge-lip** [comment]
udocker uses the tar command from the host system and produces  "Error: while extracting image layer" when tar returns a non-zero value. This can have different reasons such as:
a) problems like file system full or insufficient permissions  
b) limitations in tar or in commands invoked by tar like in the handling of sparse file formats 
c) extracting content that cannot be extracted by non-root users like creating devices. 
Notice that in most cases the errors are non fatal and the extraction continues until the end, depending on the actual reason this error might be irrelevant or important. 

When such errors occur the current solution is to recreate the container with debug as in `udocker -D create IMAGE` search for the actual tar errors and see if they are relevant for the container execution .e.g. `udocker -D create IMAGE 2>&1 | grep  '^tar.*:'`
