### ISSUE TITLE
Is it Possible to Mount FUSE Filesystems inside of Udocker Containers?

### ISSUE THREAD

**Issue by zicklag** [indigo-dc/udocker#278]
I'm trying to build an appimage inside of udocker which requires the ability to mount FUSE fileystems, but I get an "Operation not permitted" error when it tries to mount. Is there a way to give access to FUSE somehow in the container?

**Comment by jorge-lip** [comment]
You need to mount the filesystem before invoking udocker and pass then pass the directories to udocker run using -v
