### ISSUE TITLE
Unable to run container after upgrade RHEL 7.7 -> 7.8

### ISSUE THREAD

**Issue by anthosz** [indigo-dc/udocker#282]
Hello,

We have currently big performance issues on udocker since the upgrade to RHEL 7.8.

Due to this error:
`proot info: vpid 1: terminated with signal 11`

Workaround found: using `export PROOT_NO_SECCOMP=1`

Side effect: bad performances (the load between *2 et *4 (before and after)

If someone have an idea :)

Best regards,

**Comment by mariojmdavid** [comment]
issue is fixed in the new version 1.1.7
you can as well try the pre-release version that supports py3
https://github.com/indigo-dc/udocker/releases/tag/devel3_1.2.7

I will close this issue, but if you still have these error, feel free to re-open
