### ISSUE TITLE
udocker 1.1.4 hangs on all my systems

### ISSUE THREAD

**Issue by tamasgal** [indigo-dc/udocker#287]
I wanted to try out udocker but the `udocker` command with arguments hangs on every system I have tried so far. No matter if Linux or macOS. I tried Python 3.6, 3.7, 3.8 and 3.9. The `udocker` command itself gives the error message for missing command line arguments but everything else is just stuck (I waited several minutes).

Any ideas?

```
░ tgal@staticbox:~/tmp tmp took 32s
░ 11:00:37 130 > udocker
Error: parsing command line, use: udocker help

░ tgal@staticbox:~/tmp tmp
░ 11:00:41 1 > udocker help
```

```
 tgal@cca002:/sps/km3net/users/tgal/dev/pipelines  venv@master ●
░ 10:58:20 > udocker images
```

**Comment by ryanlovett** [comment]
I can reproduce on Ubuntu 20.04 where python is python3 by default. If I invoke udocker with python2 then the problem goes away.

**Comment by ryanlovett** [comment]
This was reported in https://github.com/indigo-dc/udocker/issues/77.

**Comment by sebastian-luna-valero** [comment]
Hi,

Can you try installing `udocker` with `pip install git+https://github.com/indigo-dc/udocker@devel3` instead?

I have successfully done it on all my systems, and it works!

I hope that helps,
Sebastian

**Comment by tamasgal** [comment]
It tries to write to the root directory and fails:

```
    byte-compiling /sps/km3net/users/tgal/tmp/venv/lib/python3.7/site-packages/udocker/tools.py to tools.cpython-37.pyc
    byte-compiling /sps/km3net/users/tgal/tmp/venv/lib/python3.7/site-packages/udocker/cmdparser.py to cmdparser.cpython-37.pyc
    byte-compiling /sps/km3net/users/tgal/tmp/venv/lib/python3.7/site-packages/udocker/docker.py to docker.cpython-37.pyc
    running install_data
    creating /udocker
    error: could not create '/udocker': Permission denied
    ----------------------------------------
ERROR: Command errored out with exit status 1: /sps/km3net/users/tgal/tmp/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/scratch/users/t/tgal/pip-req-build-u50o37y9/setup.py'"'"'; __file__='"'"'/scratch/users/t/tgal/pip-req-build-u50o37y9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /scratch/users/t/tgal/pip-record-d0clzksa/install-record.txt --single-version-externally-managed --compile --install-headers /sps/km3net/users/tgal/tmp/venv/include/site/python3.7/udocker Check the logs for full command output.
```

**Comment by sebastian-luna-valero** [comment]
Hi,

Could you try the next steps with a fresh python/conda install.

Pre-requisites:
* Steps for a Linux system
* Please make sure you run the steps in a new shell without a previous conda installation
* If you are using a `.condarc` file, the steps might now work depending on its configuration

Steps:
```
# Go to a new, temporary folder:
mktemp -d
cd /folder

# Download miniconda
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# Install it
bash Miniconda3-latest-Linux-x86_64.sh -b -p conda-install

# Activate conda
source conda-install/etc/profile.d/conda.sh 

# Create a new environment to work with udocker
conda create -n udocker python
conda activate udocker

# Install udocker
pip install git+https://github.com/indigo-dc/udocker@devel3

# Test it
udocker
```

If it doesn't work, please show the output of `conda info -a`

Best regards,
Sebastian

**Comment by tamasgal** [comment]
My time is unfortunately very limited the next three weeks, but may I suggest to set this test up as a CI job? We certainly do not want to repeat this exercise manually in future. The system I tried on above is CentOS 7 standard installation.

**Comment by sebastian-luna-valero** [comment]
Hi,

No worries, no rush. I just wanted to provide quick instructions that would help us understand the issues you are having.

By the way I am just an end user of `udocker`, and I do not work or collaborate with the development team.

After presenting [the HCG 16 study](https://github.com/AMIGA-IAA/hcg-16/blob/master/README.md) in one of the [ESCAPE WP3 OSS onboarding session](https://indico.in2p3.fr/event/22995/), we have successfully refactored our code to run the pipeline with `udocker` instead of `docker`, and I had just wanted to give a heads up.

Best regards,
Sebastian

**Comment by jorge-lip** [comment]
udocker 1.1.4 and 1.1.7 are for Python2 only.
For the Python 3 preview release of udocker see https://github.com/indigo-dc/udocker/blob/master/doc/installation_manual.md

**Comment by tamasgal** [comment]
> Hi,
> 
> No worries, no rush. I just wanted to provide quick instructions that would help us understand the issues you are having.
> 
> By the way I am just an end user of `udocker`, and I do not work or collaborate with the development team.
> 
> After presenting [the HCG 16 study](https://github.com/AMIGA-IAA/hcg-16/blob/master/README.md) in one of the [ESCAPE WP3 OSS onboarding session](https://indico.in2p3.fr/event/22995/), we have successfully refactored our code to run the pipeline with `udocker` instead of `docker`, and I had just wanted to give a heads up.
> 
> Best regards,
> Sebastian

Ah yeah, now I remember, I was connected to and we discussed together! 🙂 Sorry that I did not recognise you.

Install have performance issues when running our heavy machinery containers through udocker, which is unfortunately a show stopper. I'll try to spend some time in future to see if I can see what's happening or how it could be improved but vor now singularity is working solution with no hassle.

**Comment by sebastian-luna-valero** [comment]
Great, thanks!
