### ISSUE TITLE
bug in 1.1.7: argument for HostInfo().oskernel_isgreater is tuple or list, not string

### ISSUE THREAD

**Issue by mariojmdavid** [indigo-dc/udocker#289]
line 3315 PRootEngine.run
if not HostInfo().oskernel_isgreater("3.0.0"):

should be
if not HostInfo().oskernel_isgreater((3, 0, 0):

line 3709 RuncEngine.run
HostInfo().oskernel_isgreater("4.8.0"))):

should be
HostInfo().oskernel_isgreater((4, 8, 0)))):

**Comment by jorge-lip** [comment]
Fixed
