### ISSUE TITLE
Testing Pre-release devel3_1.2.7

### ISSUE THREAD

**Issue by sebastian-luna-valero** [indigo-dc/udocker#295]
Hi,

In case it helps, here is my output of testing https://github.com/indigo-dc/udocker/releases/tag/devel3_1.2.7
```
$ ./udocker --help
Traceback (most recent call last):
  File "/tmp/tmp.MLh4MJ93pZ/udocker/./udocker", line 28, in <module>
    from udocker.umain import UMain
  File "/tmp/tmp.MLh4MJ93pZ/udocker/../udocker/umain.py", line 9, in <module>
    from udocker.container.localrepo import LocalRepository
  File "/tmp/tmp.MLh4MJ93pZ/udocker/../udocker/container/localrepo.py", line 13, in <module>
    from udocker.utils.fileutil import FileUtil
  File "/tmp/tmp.MLh4MJ93pZ/udocker/../udocker/utils/fileutil.py", line 13, in <module>
    from udocker.helper.hostinfo import HostInfo
  File "/tmp/tmp.MLh4MJ93pZ/udocker/../udocker/helper/hostinfo.py", line 12, in <module>
    from udocker.utils.fileutil import FileUtil
ImportError: cannot import name 'FileUtil' from partially initialized module 'udocker.utils.fileutil' (most likely due to a circular import) (/tmp/tmp.MLh4MJ93pZ/udocker/../udocker/utils/fileutil.py)
```

Best regards,
Sebastian

**Comment by mariojmdavid** [comment]
hi, I am aware of it, fixing it as we speak

**Comment by sebastian-luna-valero** [comment]
Great, thanks!

Happy to help with the testing on my end.

**Comment by mariojmdavid** [comment]
please try again
remove dirs udocker and .udocker
I have not bumped the version yet since I am waiting for Jorge to have the bin and lib compiled including crun, for cgroups2 (at least for the latest fedora)
so it's still devel3_1.2.7
I have tested yesterday on several linuxes and all went well (except on py3.5 in ubuntu16.04)
give us feedback

**Comment by sebastian-luna-valero** [comment]
Hi,

I don't see new commits in https://github.com/indigo-dc/udocker/commits/devel3_1.2.7

Is that correct?

**Comment by mariojmdavid** [comment]
all commits on
https://github.com/indigo-dc/udocker/tree/devel3

pre-release in
https://github.com/indigo-dc/udocker/releases/tag/devel3_1.2.7

so just copy paste
wget https://github.com/indigo-dc/udocker/releases/download/devel3_1.2.7/udocker-1.2.7.tar.gz
tar zxvf udocker-1.2.7.tar.gz
export PATH=`pwd`/udocker:$PATH

**Comment by sebastian-luna-valero** [comment]
Alright, thanks!

Here are my testing steps for future reference:
```
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p conda-install
source conda-install/etc/profile.d/conda.sh 
conda create -n udocker python
conda activate udocker

wget https://github.com/indigo-dc/udocker/releases/download/devel3_1.2.7/udocker-1.2.7.tar.gz
tar xzf udocker-1.2.7.tar.gz 
cd udocker/
./udocker --help
```

The `./udocker --help` command worked successfully on 4 virtual machines with CentOS 7, CentOS 8, Ubuntu 18.04 and Ubuntu 20.04. Python was version `3.9.1`

Is there anything else I can help with?

Many thanks,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Hi again,

FYI, we are now testing the Python 3 development version for one of our workflows:

https://github.com/AMIGA-IAA/hcg-16/pull/8

It looks like it's working!

Best regards,
Sebasian

**Comment by sebastian-luna-valero** [comment]
It's working so I will close this issue.

Many thanks for this great tool! Please feel free to ping me if you need further testing!
