### ISSUE TITLE
Can't supply login credentials in devel3

### ISSUE THREAD

**Issue by davidjsherman** [indigo-dc/udocker#310]
I haven't been able to supply login credentials using version 1.2.7 from the devel3 branch

1. PR #308: The base64 encoding of the username:password pair fails because [base64.b64encode requires a bytes-like object](https://docs.python.org/3/library/base64.html).
2. PR #309: The keystore code seems to have been changed to report a Unix-style exit status for put and delete, but **do_login** still thinks this is a Boolean success value.

**Comment by davidjsherman** [comment]
My two one-line PRs fail in CI because Git can't check out the branch, I don't know what to do about that

**Comment by jorge-lip** [comment]
It is fixed in devel3

**Comment by jorge-lip** [comment]
Included and fixed in v1.3.0. Please reopen if problem persists. 
Many thanks
