### ISSUE TITLE
[joss review] installation instructions & dependencies

### ISSUE THREAD

**Issue by mviereck** [indigo-dc/udocker#311]
Hello,

I am @mviereck, one reviewer of your submisson at https://github.com/openjournals/joss-reviews/issues/3295.

Yet I look at installation instructions and dependency declaration.
Partially I found it a bit unclear and thought to write it down as the impressions are fresh from a non experienced new user.

An unpolished list from first impressions:

----------
> 1. DEPENDENCIES

> Python dependencies are described in the file requirements.txt.

I am lucky to have all dependencies fulfilled as it seems. At least I get no error. Users with rather low experience who get errors might have problems to check or fulfill the python dependencies. How to check, what to do? Why is the list in a separate file at all?

> Other host libraries and tools required: [...] 

It might help to write `tar` and `find` instead of tar and find (and others).

Proposal: Provide a package list for some major distributions, maybe also with `apt install` and `dnf install` examples. For comparision, a [dependency table](https://github.com/mviereck/x11docker/wiki/dependencies#recommended-base) I've set up once for another project.

---------------
> 2.1. PYTHON2: INSTALL DIRECTLY FROM GITHUB

So far, the instructions are clear and straightforward. But:

> downloading and installing the udockertools will be performed automatically.

Maybe give a short explanation here already that those are binaries stored in `~/.udocker` and are build from source in the same repo. From first impression it is not clear what the udockertools are, from where they come and where they are stored. Those information can be obtained further down, though, but in parts that are not core installation instructions.

2.1 to 2.4 are independent full installations. 
2.5 is not.
2.6? Not sure

3. to 6. are not exactly installation instructions. 

I recommend to overthink the structure.
 
-------------
Missing: Is there an `udocker uninstall`? How to cleanly remove udocker and maybe also images and containers?

**Comment by vsoch** [comment]
I second this - it would be good to have a getting started guide that gives some help to installing dependencies, beyond the name in text. https://github.com/openjournals/joss-reviews/issues/3295

**Comment by mviereck** [comment]
I had a closer look at the udockertools.
I found that those are binaries from third party repositories with their own licenses and the source code stored elsewhere. The binaries are stored as tarball in the udocker releases too, if I see right.
This need to be clarified in the documentation:
 - a list of all third party tools and their origin repositories
 - all licenses
 - source location of all tools

**Comment by mviereck** [comment]
Just want to note, that the third party tools of udocker are not clearly stated and are missing source, license and origin. This needs to be documented well. In the current state this is an acceptance blocker. Compare https://github.com/indigo-dc/udocker/issues/311

**Comment by jorge-lip** [comment]
We change the dependencies section and placed in the beginning of the installation manual. The dependencies file had al dependencies necessary both for usage but also for development and testing within our Jenkins. The actual dependencies for normal usage are smaller and we made that more clear.

The list of tools was already in the manuals and in the acknowledgments. The licenses are shipped in the udockertools tarball, but we were not extracting them upon installation. Now since the just release version 1.3.0 we are extracting the licenses of the tools and libraries to the installation directory ($HOME/.udocker/doc).

The source code for the tools is in separate repositories. For runc and crun we just take the software from the upstream source code repositories and we make minor changes to produce static binaries. For Proot and Fakechroot we have cloned repositories with all the required changes. Some we have pushed already upstream. All the required steps for building the tarball are in the build script in utils/build_tarball.sh

The repositories containing the source code are now described in the documentation 
https://github.com/indigo-dc/udocker/blob/master/docs/installation_manual.md#6-source-code-for-the-tools-and-libraries)

**Comment by mviereck** [comment]
The structure of the installation instructions looks better overall.
However, I am still missing some core points:
 - Please explicitly state that `udocker install` installs third party tools.
 - Give also a link to the origin of the third party tools, not only to forked repositories.
   - > we make minor changes to produce static binaries.

      Please note this, too.
 - Please explicitly list every licenses at each tool, also with a link to see the full license.
 
Minor detail: The links should be clickable, not only copy&paste. (I refer to the link given on the main site: https://indigo-dc.github.io/udocker/installation_manual.html)

> The list of external tools to support the actual execution was already in the manuals and in the acknowledgments. 

You could have pointed me to this. I only found general notes mixing installed udocker-tools like proot with non-installed tools like singularity.

**Comment by jorge-lip** [comment]
The tools used are now listed in tables in section 6 together with the repositories and licenses.

**Comment by vsoch** [comment]
@jorge-lip this looks much better! I have one more tiny request - could you please put the documentation URL https://indigo-dc.github.io/udocker/ in the GitHub description (e.g., when you click edit) so it's front and center without needing to scroll down to the README.

**Comment by jorge-lip** [comment]
@vsoch thanks, I forgot to add it, the documentation URL is now there.

**Comment by vsoch** [comment]
I'm good to resolve this issue - let's wait for @mviereck to comment.

**Comment by mviereck** [comment]
Yes, this looks way better now, thank you!
One remaining point:
 -  In "2.1. Install from a released version", please adjust the sentence "Complete the installation by invoking udocker install to download and install the tarball containing the tools and libraries required to execute containers:". 
    - A note at this point that `udocker install` installs third party tools.
    - A link down to chapter "6. External tools and libraries".

**Comment by jorge-lip** [comment]
Thanks, these fixes have been added to the installation manual.

**Comment by mviereck** [comment]
Thank you! Now I am entirely fine with installation instructions and dependency declaration.
