### ISSUE TITLE
[joss review] possible license conflict?

### ISSUE THREAD

**Issue by mviereck** [indigo-dc/udocker#335]
udocker is distributed under Apache License 2.0.
The third party tools have more restrictive licenses, notable GPLv2 and GPLv3.

I am not familiar with details in deep of the licenses.
But AFAIK because udocker hardly depends on the third party tools, it can only be used in the most restrictive combination of all licenses, likely GPLv3.

I point to this because users might use udocker or redistribute e.g. in a commercial way that might be forbidden by the other licenses.

I am not sure how to resolve this, just want to point on a possible issue. 

https://github.com/openjournals/joss-reviews/issues/3295

**Comment by mariojmdavid** [comment]
please suggest what we should do, but keep in mind
there where/are several people contributing to the SW and have done so under the current license
and there are currently 95 forks

**Comment by jorge-lip** [comment]
The Apache License 2.0 is for udocker only, the other tools retain their original licenses and we make the source code changes public. What is done by udocker is not different than a Linux distro does by distributing multiple software with multiple licenses. The problem with mixed licenses arises typically when a single indivisible object incorporates code with multiple licenses. That is not the case of udocker itself that is a Python script and is not linked against those other codes.

**Comment by mviereck** [comment]
> The Apache License 2.0 is for udocker only, the other tools retain their original licenses and we make the source code changes public. What is done by udocker is not different than a Linux distro does by distributing multiple software with multiple licenses. The problem with mixed licenses arises typically when a single indivisible object incorporates code with multiple licenses. That is not the case of udocker itself that is a Python script and is not linked against those other codes.

Yes, I agree.

> please suggest what we should do

As I've said, I am not sure myself.
Basically a user must be aware which licenses he must regard if going further than personal use, especially in case of redistribution. This is one reason why I've insisted on a list of licenses and origin of `udocker-tools`. 

A quick solution would be a hint like:
_"Redistribution and commercial use must regard all licenses shipped with udocker`."_
This is formally correct and enough, but leaves the user to figure out the consequences himself.

It would help the user to give some hints on the consequences. Though, I can't tell the consequences myself, I am not an expert in interfering software licenses. (Is _anyone_ an expert in this?)

**Comment by jorge-lip** [comment]
Agree I have added the suggested statement to the README, to the introduction of the installation manual and also in the licenses section of the installation manual. The full statement is:

Redistribution, commercial use and code changes must regard all licenses shipped with udocker. These include the [udocker license](LICENSE) and the individual licences of the external tools and libraries packaged for use
with udocker. For further information see the [software licenses section](https://indigo-dc.github.io/udocker/installation_manual.html#62-software-licenses) of the installation manual.

**Comment by mviereck** [comment]
This looks good to me, thank you!
