### ISSUE TITLE
[joss review] list of contributors

### ISSUE THREAD

**Issue by mviereck** [indigo-dc/udocker#348]
Your paper lists the following contributors:
 - Jorge Gomes 
 - Mario David 
 - João Martins 
 - João Pina 
 - Samuel Bernardo 
 - Isabel Campos 
 - Pablo Orviz 
 - Alvaro López-García

The [github contributors list](https://github.com/indigo-dc/udocker/graphs/contributors) shows that most contributions are done by Jorge Gomes and Mario David. Other contributions are minor (mostly a few lines).

What is the contribution of the others mentioned in the paper? 
Why don't they appear as contributors on github?

https://github.com/openjournals/joss-reviews/issues/3295

**Comment by jorge-lip** [comment]
Yes not all the authors are contributing with code. All the persons listed as authors in the paper have contributed to udocker in different ways including the concept, design, requirements, reviews, documentation, SQA implementation and validation of the releases against use cases. Don't know if there is a requirement in JOSS that only code contributors can be authors so please advise.

**Comment by mviereck** [comment]
Did it really need 4 weeks to give this answer?
I am annoyed.
If you are not interested in finishing the review, please tell us.

For the review I have to check if the list of authors seems to be appropriate.
