### ISSUE TITLE
Storing containers/images in different path

### ISSUE THREAD

**Issue by matq007** [indigo-dc/udocker#357]
Hi, is it possible to customize udocker's config to store the images/containers in different folder than home directory? Some HPC systems are set with a limited space on home folder making it cumbersome to store many multiple containers.
Thank you :)

**Comment by mariojmdavid** [comment]
hi, yes
check in the installation manual the setting of environment variables, to install or have the images and containers in custom dirs
https://indigo-dc.github.io/udocker/installation_manual.html#5-environment-variables

**Comment by matq007** [comment]
Perfect, totally missed it. Thank you very much 🙂
