### ISSUE TITLE
regression: docker.io/python:3-slim no longer works

### ISSUE THREAD

**Issue by mr-c** [indigo-dc/udocker#359]
in udocker 1.1.3 `udocker pull docker.io/python:3-slim` worked

but in udocker 1.3.1 that fails; one has to either use the default registry via  `udocker pull python:3-slim` or add in `library`: `udocker pull docker.io/library/python-3:slim`

It would be nice if the 1.1.3 behavior was restored; thanks!

**Comment by mr-c** [comment]
This persists with udocker 1.3.4

**Comment by mr-c** [comment]
I tested the udocker [1.3.5 tag](https://github.com/indigo-dc/udocker/releases/tag/1.3.5) (a.k.a. https://github.com/indigo-dc/udocker/commit/fc3ecfcace6844aa624e9466a3b410ee12aa47a0 ) and the issue persists. It would be nice if `udocker` resumed the 1.1.3 behavior, thus matching `docker` itself. Thanks!

**Comment by mariojmdavid** [comment]
solved in 1.3.5

**Comment by mr-c** [comment]
I can confirm the fix, thank you @mariojmdavid !
