### ISSUE TITLE
Error: installation of udockertools failed

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [indigo-dc/udocker#362]
Getting below errors/warnings after running `udocker install --force`

| Logs|
|---|
|udocker command line interface version: 1.3.1|
|requires udockertools tarball release : 1.2.8|
|Info: udocker command line interface 1.3.1|
|Info: searching for udockertools 1.2.8|
|Install Log: False|

What could be the reason for this?

udocker version I'm using: `1.3.1`

**Comment by eugeniosss** [comment]
I am running in the exact same problem... If you found a solution please let me know!

**Comment by mariojmdavid** [comment]
sorry what errors/warnings
if need be post
udocker --debug install --force

**Comment by RadFromOrange** [comment]
Hi , i am stuck at udockertools download .


udocker command line interface version: 1.3.5 
requires udockertools tarball release : 1.2.8
Info: searching for messages:
curl url:  https://raw.githubusercontent.com/indigo-dc/udocker/master/messages
curl arg:  {'ofile': '/tmp/udocker-9839-4edbe4dd-eeb3-3abd-8932-b0acb0d4e966-udockertools', 'follow': True}
* Uses proxy env variable no_proxy == 'localhost'
* Could not resolve host: raw.githubusercontent.com
* Closing connection 0
Error: in download: Could not resolve host: raw.githubusercontent.com
Info: no messages:  https://raw.githubusercontent.com/indigo-dc/udocker/master/messages
Error: installation of udockertools failed


How can i download udockertools  behind corporate proxy , i have tried setting https_proxy with no success.
how can i install udockertools  manualy ?

Thx,

**Comment by RadFromOrange** [comment]
> hi check the following in the installation manual https://github.com/indigo-dc/udocker/blob/master/docs/installation_manual.md section 2.4
> 
> this way you will pre-fetch the udocker-tools and install in some host without outbound
> 
> after if you want to pull (or search) images in dockerhub (or other repository)
> 
> make a ssh tunnel
> 
> ssh -D 9000 -q -C -N -f user@
> 
> and
> 
> udocker pull --httpproxy=socks5h://localhost:9000 <image_name you want>

Thx  ! it worked
