### ISSUE TITLE
Running Udocker inside Proot-Distro?

### ISSUE THREAD

**Issue by Root-voidX** [indigo-dc/udocker#364]
Hello everyone,

So I am attempting to run udocker on Fedora 35 running inside proot-distro in termux on an android phone. I installed udocker and pulled an arm image of centos 7 and created the container, However when I try to run it (i made use to change exec mode to P1 for proot), it says the following:

![Screenshot_20220724-023943_Termux](https://user-images.githubusercontent.com/24353606/180635673-143990a9-d5cc-43e3-a68a-c594ef821e5b.jpg)

however when I tty to run any command, its running the command for fedora and not the container? Am I doing something wrong?

**Comment by jorge-lip** [comment]
udocker mode P1 and P2 make use of PRoot. Running udocker P1 or P2 inside PRoot will likely fail and is not supported.
