### ISSUE TITLE
Ignore image loading if already exists

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [indigo-dc/udocker#378]
Can we ignore the loading image if the given repo and tag already exist, and instead of raising an error log we can just log as INFO right?

https://github.com/indigo-dc/udocker/blob/bd523eab3d5557a3d49c6583b5c3fe8b36212c38/udocker/commonlocalfile.py#L53

**Comment by mariojmdavid** [comment]
agree,
and there where a few other places that it makes sense to change the msg level to info
implemented in branch dev-v1.3.6

**Comment by mariojmdavid** [comment]
release 1.3.6
