### ISSUE TITLE
Udocker in chroot

### ISSUE THREAD

**Issue by HKTangyuan** [indigo-dc/udocker#383]
当我在chroot_nethunter环境中尝试运行udlcker的容器时，它出现了报错：proot info: pid 10370: terminated with signal 11。
When I tried to run the container of udlcker in the chroot_nethunter environment, it reported an error: proot info: pid 10370: terminated with signal 11.
![image](https://user-images.githubusercontent.com/109419998/213587823-510bb450-dcd0-474e-bbf5-d8733fbcccdc.jpeg)

**Comment by DanielWahl** [comment]
Hey,
how did you manage to fix this issue? I have the same problem.

**Comment by HKTangyuan** [comment]
> Hey,
> how did you manage to fix this issue? I have the same problem.

这个报错在我分析后得到了解决
这个报错可能意味着你的系统架构可能不兼容容器架构
This error was solved after my analysis.
This error may mean that your system architecture may not be compatible with the container architecture.
