### ISSUE TITLE
Udocker pulls image for the wrong processor architecture

### ISSUE THREAD

**Issue by ddscentral** [indigo-dc/udocker#388]
udocker pull pulls image for the wrong processor architecture.
When running under arm64, amd64 (aka. x86-64) image is pulled, even though a native arm64 image is available for that container. Correct behavior should match that of "docker pull" command: try to pull image for the host machine architecture first and if it isn't available, display a warning and pull image for a different architecture, usually amd64.

Platform: Android (Termux)

**Comment by dhanar10** [comment]
I am encountering the same problem trying to use udocker in termux. I tried to figure out what's wrong by running `udocker -D pull hello-world`. Looking at the debug output, it seems like udocker is fetching manifest v2 version 1 instead of version 2. I think this is probably the problem because according to docker docs I read, it looks like multi arch requires manifest v2 version 2. But CMIIW.

**Comment by ddscentral** [comment]
I've noticed the manifest issue as well. Did some digging in the code but could not find a reason why.
I work-arounded this issue by adding support for pulling images by their SHA256 hashes (Docker syntax: docker pull imagename@sha256:<hash>).
This allows me to force udocker to request a specific image instead of a tag. Not the most convenient way, but it does the job.
I can upload a patched version if anyone needs it (the code would require some cleaning-up for a proper PR).

**Comment by dhanar10** [comment]
@ddscentral Nice! I am interested with your patched  version of udocker. I will be thankful if you can share it somewhere.

**Comment by ddscentral** [comment]
Link: [udocker-1.3.7-patched-DDSC.tar.gz](https://zebra.ddscentral.org/pub/downloads/termux/udocker-1.3.7-patched-DDSC.tar.gz)

Changes:
* Support for pulling images by sha256 hash.
* Support for QEMU user-mode emulation. Set QEMU_PATH environment variable to your qemu-user binary (eg qemu-x86_64) before executing "udocker run" command.

I made this fork for my own uses and will not provide support for it. Code cleanup is welcome.

**Comment by dhanar10** [comment]
@ddscentral I have a couple of questions about your fork.

1. You added qemu multiarch stuff, so the use case is to run x86 image on arm, am i understanding it correctly?

![image](https://user-images.githubusercontent.com/4580548/235087873-8a555826-f918-43b0-a878-e84b4e658240.png)

2. Why did you add proot link2symlink here? What problem you are trying to solve here?

![image](https://user-images.githubusercontent.com/4580548/235088275-7b479c40-0900-44ce-9148-8c346873a294.png)

**Comment by ddscentral** [comment]
1. Yes, this allows to run images made for a different processor architecture (eg. x86 on ARM).
Similar to https://github.com/tonistiigi/binfmt but in userspace and without requiring binfmt support.
2. Sorry, my comment probably isn't the clearest. Proot with link2symlink is required to workaround permission issues when extracting Docker images which contain hardlinks. This option converts them to symlinks.

**Comment by ddscentral** [comment]
Another note: when running udocker under Termux, you will need to replace "proot" binary installed by Udocker with Termux version as the stock one will not work on Android.

**Comment by jorge-lip** [comment]
This issue should be fixed in release 3.9.

**Comment by mariojmdavid** [comment]
release 1.3.11 created
