### ISSUE TITLE
Getting "Error: Invalid container name format", when trying to run a container

### ISSUE THREAD

**Issue by ypanagis** [indigo-dc/udocker#391]
I am using `udocker` in Ubuntu 22.04 running inside Parallels. I am trying to use the `docker` container available at `eltedh/nosketch-engine:latest`. `udocker ps` gives me a list of containers for example

    CONTAINER ID                         P M NAMES              IMAGE               
    90b706f2-26e4-390b-95c7-2a1b031e703e . W ['noske']          eltedh/nosketch-engine:latest

but a simple `udocker run --rm --name=['noske'] eltedh/nosketch-engine:latest`, gives `Error: invalid container name format`. I get the same error even when giving `--name='noske'` or `--name=noske`. I named the container after pulling it, by giving `udocker name CONTAINER_ID noske`

From a simple search at the repository, it seems that the error is printed from `cli.py`, when the script cannot set the name to a specific container. 

Any ideas on what is wrong, perhaps even in my execution flow?

**Comment by dcg601** [comment]
Silly error, I was giving `--name=['noske']` instead of `--name==noske`. I was basically missing double `=`.... Please close the issue
