### ISSUE TITLE
Cannot pull ubuntu:latest from Docker hub, it is now an OCI index file

### ISSUE THREAD

**Issue by Tuupertunut** [indigo-dc/udocker#392]
**Udocker version:** 1.3.8

**How to reproduce**
- Download Udocker 1.3.8
- Run `udocker pull ubuntu:latest`
- Observe the error:
```
Error: pulling manifest:
Error: no files downloaded
```

**Why it happens**

`ubuntu:latest` in Docker hub now returns an OCI index file. Udocker does not understand that format, so it fails to pull the `ubuntu:latest` image.

**Comment by jorge-lip** [comment]
It will be fixed in the upcoming 1.3.9 that is already available in the devel3 branch

**Comment by mariojmdavid** [comment]
1.3.9 released
