### ISSUE TITLE
udocker load in rhel cluster doesn't work on saved tar docker image

### ISSUE THREAD

**Issue by itaiwe** [indigo-dc/udocker#395]
Hi,
I have built an image on my pc using wsl with docker and I wanted to move it to a gpu cluster I have through the organization and run it there.
The organization uses udocker. udocker version returned 1.3.8.
Here is the output from the attempt at loading the image:
```
$ udocker load -i CompareRL/comparerldocker.tar
Info: already installed, installation skipped
Info: repository and tag already exist comparerldocker latest
Error: load failed
```

**Comment by mariojmdavid** [comment]
apologies if you tried this already

udocker images - does it have the image registered there already?
if yes, udocker rmi <imageName>

if not

udocker -D load -i CompareRL/comparerldocker.tar

to get more debug info and send us

another possibility is for you to send us (somehow) the tar file IF it's not private of course

**Comment by mariojmdavid** [comment]
inactive for several months, please reopen if necessary
