### ISSUE TITLE
Cannot  push saved tarball as rootFs is missing in json. Invalid image config (rootFS is not set)

### ISSUE THREAD

**Issue by RadFromOrange** [indigo-dc/udocker#398]
Hi,

Nice project , i am using it for rootless world .

I am trying to push toregistry a saved tarball to dockerhub with skopeo but it seems that the tarball is missing some data like rootfs.

_FATA[0000] determining manifest MIME type for docker-archive:///workspaces/umoci/popo.tar: Invalid image config (rootFS is not set): 93dc8da4000dde62aefe8ed8c2647b711e6ffe9c6940d6e0e61c18c2d001ca5c.json_ 

here is the full use case : (pulling alpine , make some changes , export container , import container , save image )

![image](https://github.com/indigo-dc/udocker/assets/47286056/cc5b2209-c793-46c2-9643-c84ba8bd4439)

May be ma i missing something in the workflow ?

Thx,

**Comment by RadFromOrange** [comment]
Here is the tarball:

[savedImage_.zip](https://github.com/indigo-dc/udocker/files/12719077/savedImage_.zip)

**Comment by jorge-lip** [comment]
This is now implemented in the Devel3 branch. The limitation was in the import when udocker creates the metadata.
Please check.

**Comment by RadFromOrange** [comment]
I have tested it on devel3 Branch. It works !

Thanx a lot!

![image](https://github.com/indigo-dc/udocker/assets/47286056/111043fb-cdc4-413e-b185-3f080912928e)

**Comment by RadFromOrange** [comment]
closing it

**Comment by mariojmdavid** [comment]
release 1.3.11 published
