### ISSUE TITLE
config udocker output is not working

### ISSUE THREAD

**Issue by Wanli-HE** [indigo-dc/udocker#405]
HI!

the default ouput of udcoker is in ".udocker", so i am trying to config it to other folder, but it seems not works, i intall udocker by pip, and copy the  udocker.conf to the folder ".udocker", and config it like blow, 
"""[DEFAULT]

# Verbosity level according to udocker Msg
verbose_level = 3

topdir = "/home/projects/udocker/"
bindir = "/home/projects/udocker/bin"
libdir = "/home/projects/udocker/lib"
reposdir = "/home/projects/udocker/reposdir"
layersdir = "/home/projects/udocker/layersdir"
containersdir = "/home/projects/udocker/containersdir"

dockerio_index_url = https://hub.docker.com
dockerio_registry_url = https://registry-1.docker.io
#tarball_release = 1.2.8
#tarball =
tmpdir = /tmp
keystore = keystore
#use_curl_exec =
default_execution_mode = P1
#http_proxy =
"""

but actually the images were not download in the aims folder, and also not in ",udocker" folder,

di you have any suggestion on that?

best,
wanli

**Comment by jorge-lip** [comment]
Please remove the quotes or use the environment variables like UDOCKER_DIR

`topdir = /home/projects/udocker/
bindir = /home/projects/udocker/bin
libdir = /home/projects/udocker/lib
reposdir = /home/projects/udocker/reposdir
layersdir = /home/projects/udocker/layersdir
containersdir = /home/projects/udocker/containersdir`

**Comment by mariojmdavid** [comment]
besides @jorge-lip comment above
if you have your udocker.conf file in /home/projects/udocker.conf
you should invoke udocker the following way to use the conf file

udocker --config=/home/projects/udocker.conf <any command>
