### ISSUE TITLE
dpkg error

### ISSUE THREAD

**Issue by mobin-mazahery-school** [indigo-dc/udocker#412]
when installing udocker in a docker environment dpkg has problems with `/var/lib/dpkg/status-old` file. 
`dpkg: error: error creating new backup file '/var/lib/dpkg/status-old': Operation not permitted`

- Image: Ubuntu
- DockerImage: quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-jre
 
![image](https://github.com/indigo-dc/udocker/assets/98708517/205dfa1a-c2e3-45a0-bb39-e52484097514)

**Comment by mobin-mazahery-school** [comment]
@mariojmdavid

**Comment by mobin-mazahery-school** [comment]
I have tested different docker images and all have the same problem

**Comment by RadFromOrange** [comment]
Same error,got this when doing an Apt install inside a container

**Comment by RadFromOrange** [comment]
thx, for me it's 1.3.11

**Comment by mobin-mazahery-school** [comment]
I had the latest one. I use pip to install it. I guess it was 1.3.11 or .12. execmode was default one

**Comment by mariojmdavid** [comment]
solved in 1.3.13 upcoming release

**Comment by mariojmdavid** [comment]
1.3.13 released
