### ISSUE TITLE
Import with no tag behave differently in docker and udocker

### ISSUE THREAD

**Issue by romainreuillon** [indigo-dc/udocker#46]
```
[reuillon:~/Install/udocker] devel 40m49s 1 ± udocker import /tmp/httptest.tar
Error: must specify image:tag or repository/image:tag
[reuillon:~/Install/udocker] devel 40m52s 1 ± docker import /tmp/httptest.tar
sha256:18dbdb39a6771699559b97594997f4bdf7ff9b2b81d2d874924e58ab1304f465
```

**Comment by jorge-lip** [comment]
Not possible to fix in short time.
Docker does it because uses IDs and thus can create images without names.
udocker does not use IDs for the images (for images udocker only uses names/tags), that's why an image name is required.

**Comment by mariojmdavid** [comment]
latest pre release version 1.2.9 from devel3 this is solved

  udocker import ub.tar ubuntu
  Info: added layer cdf9b77bcfed92625077f67af33e63517bfc0d6985451a6c15dd7b369c7bb936

  udocker images
  REPOSITORY
  ubuntu:latest

Also

  udocker import ub.tar ubuntu:20.04
  Info: added layer 8c8134e42a253f3b5891e0614ce57a07b2c810cdc5fd7d85a088c6c585c1f2d3
  udocker images
  REPOSITORY
  ubuntu:20.04                                                 .
  
thus this is solved and closed
