### ISSUE TITLE
udocker ignores further elements in ENTRYPOINT JSON array

### ISSUE THREAD

**Issue by bagnasco** [indigo-dc/udocker#53]
Apparently udocker misses any elements in the JSON array passed in the ENTRYPOINT statement in a dockerfile.

Say I have a container running a python scripts, with arguments. I
want the script name to be in the entry point, and provide default
arguments via CMD, something like

```
ENTRYPOINT [“/usr/bin/python”,”myscript.py”]
CMD [“100”]
```
This works in Docker, while udocker apparently misses the second
piece in the array, since the outcome is 
```
/usr/bin/python: can't open file ’100': [Errno 2] No such file or directory
```
which I assume means it is passing “100” as an argument directly to
/usr/bin/python.

**Comment by jorge-lip** [comment]
Fixed in master branch
