### ISSUE TITLE
Cannot Run Alpine-based images with Fakechroot (F1) Execution Mode

### ISSUE THREAD

**Issue by gmolto** [indigo-dc/udocker#76]
Hi,

Attempting to run a Docker container based on the alpine:latest Docker image using uDocker with the F1 execution mode results in the following error:
```
udocker create --name=test-alpine alpine:latest
udocker setup --execmode=P1 test-alpine
udocker run test-alpine sh

_Warning: running as uid 0 is not supported by this engine
Warning: non-existing user will be created
Error: command not found or has no execute bit set:  ['sh']_
```
Since many commands are symlinks to /bin/busybox, attempting to execute that results in:
```
udocker run test-alpine /bin/busybox

_Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: __snprintf_chk: symbol not found
Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: __vfprintf_chk: symbol not found
Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: __chk_fail: symbol not found
Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: rawmemchr: symbol not found
Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: __memmove_chk: symbol not found
Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: __rawmemchr: symbol not found
Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: __strcpy_chk: symbol not found
Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: __fprintf_chk: symbol not found
Error relocating /home/ubuntu/.udocker/lib/libfakechroot-Ubuntu-16-x86_64.so: __sprintf_chk: symbol not found_
```

Is there any workaround to this issue? Changing the execution mode to Proot solves the problem but we need to stick to the F1 execution mode.

Thank you in advance.

**Comment by nozpheratu** [comment]
Any news on this? I'm running udocker on AWS Lambda and being able to use Alpine would open a lot of doors for me with the reduced image size.

**Comment by shatgupt** [comment]
Just wanted to let the maintainers know that I am also looking for the same use case as @nozpheratu and this enhancement would greatly benefit me.

**Comment by jorge-lip** [comment]
Version 1.1.3 has some experimental code for Alpine.

**Comment by gmolto** [comment]
Thanks @jorge-lip for such great enhancement. Initial testing carried out by @alpegon reveals that this new version of udocker works in AWS Lambda as well. Support in SCAR is being tracked in https://github.com/grycap/scar/issues/28#issuecomment-440316583

**Comment by gmolto** [comment]
We already integrated successfully udocker 1.1.3 in [SCAR](https://github.com/grycap/scar) and now Alpine-based images can be used in AWS Lambda. Thank you again for such great work. Closing the issue.
