### ISSUE TITLE
Udocker not working with python 3

### ISSUE THREAD

**Issue by alpegon** [indigo-dc/udocker#77]
Hi, when executing udocker in a python 3 environment I get the following error:
```
Traceback (most recent call last):
  File "udocker", line 5844, in <module>
    sys.exit(Main().start())
  File "udocker", line 5757, in __init__
    if not self.cmdp.parse(sys.argv):
  File "udocker", line 5618, in parse
    if arg[0] in string.letters:
AttributeError: module 'string' has no attribute 'letters'
```
Looks like an incompatibility with the python libraries.
Are you planning on supporting python 3?

Thanks

**Comment by mariojmdavid** [comment]
work ongoing on devel3 branch, largely done

**Comment by sebastian-luna-valero** [comment]
+1!

**Comment by mr-c** [comment]
Thanks for the Python 3 progress. As a reminder it will be possible and perhaps common for users of the next Debian release (and other Linux distributions) to have Python 3 but no Python 2.

**Comment by mariojmdavid** [comment]
pre release 1.2.9 soon to be released, considered solved
