### ISSUE TITLE
parsing of command to run in container doesn't match Docker

### ISSUE THREAD

**Issue by mr-c** [indigo-dc/udocker#87]
Docker correctly handles complex quoting and redirection
``` 
$ docker run python:2-slim /bin/sh -c "echo '{"foo": {"location": "file:///"}}' > /dev/stdout"
{foo: {location: file:///}}
$
```
But udocker doesn't
```
$ udocker run python:2-slim /bin/sh -c "echo '{"foo": {"location": "file:///"}}' > /dev/stdout"
 
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING cce0587e-eeec-35ba-ba7f-eb936f9a846f                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: sh
{foo:
$
```

**Comment by jorge-lip** [comment]
Fix added in devel branch

**Comment by mr-c** [comment]
I can confirm, thanks!

When is the next release scheduled or anticipated?

**Comment by jorge-lip** [comment]
Version 1.1.1 will be released in November.
If you have contributions ;) please make the pull requests against the devel branch.

**Comment by mr-c** [comment]
@jorge-lip Will do! You can alert other contributors to the preferred branch for PRs by adding a brief [contributing guide](https://github.com/nayafia/contributing-template#contributing-guides-a-template) that will show up automatically when they open a pull request
