### ISSUE TITLE
Publication of udocker

### ISSUE THREAD

**Issue by psafont** [indigo-dc/udocker#88]
Hello,

Is there a chance udocker would be uploaded to PyPI for ease of use?

Also, in https://github.com/indigo-dc/udocker/blob/master/doc/installation_manual.md the address to download udocker does not exist in the server, latest uploaded version is 1.0.1: http://repo.indigo-datacloud.eu/repository/indigo/1/centos7/x86_64/tgz/

**Comment by jorge-lip** [comment]
Hi, 

Thanks for the tip I will see to it. 
Meanwhile I fixed the documentation with the correct location for 1.1.0.

**Comment by psafont** [comment]
Thanks!

**Comment by mariojmdavid** [comment]
done
pip install udocker
installs 1.1.3-patch1
