### ISSUE TITLE
Cannot run udocker inside a container

### ISSUE THREAD

**Issue by psafont** [indigo-dc/udocker#91]
I'm getting `Error: do not run as root !`, any chance this behaviour might be modified? :)

I want to use it in a container since some CI run steps inside containers, this is useful for running workflows:
`docker run --rm --volume=$PWD:/tmp/workdir -w=/tmp/workdir me/cwltool-udocker cwltool --user-space-docker-cmd=udocker pack/pack.cwl pack/jobs/lab-mod.yml`

**Comment by jorge-lip** [comment]
udocker does not offer isolation and the code as not been developed to safely run as root.
I strongly discourage running udocker as root. 
I added the switch --allow-root in the devel branch.

udocker  --allow-root  run container

**Comment by psafont** [comment]
Thanks for being so fast!

@mr-c gave me a solution, forcing docker to use a particular user in the container, like this:

`docker run --user ${USER} --rm --volume=$PWD:/tmp/workdir -w=/tmp/workdir me/cwltool-udocker cwltool --user-space-docker-cmd=udocker pack/pack.cwl pack/jobs/lab-mod.yml`
