### ISSUE TITLE
Home directory not correct

### ISSUE THREAD

**Issue by system123** [indigo-dc/udocker#92]
I have been experiencing an issue with udocker which does not respect the home directory which is set in the original docker container. In my Dockerfile I specify 

`
ENV USER root
ENV HOME /root
WORKDIR $HOME
`

However, when running this container with uDocker the HOME env variable is overwritten to 

`
root@blah:/root# echo $HOME
/
`

If I try specify the home directly via the -e HOME=/root in the run parameters nothing changes and I still have an incorrect home directory for root.

I think the env variables are parsed too early and are being overwritten by some hard coded default. If the original docker container HOME env variable cannot be kept, there should at least be a manual method to set the specific HOME environment variable via the run parameters.

**Comment by mr-c** [comment]
Hello @system123 

I ran into the same issue: https://github.com/indigo-dc/udocker/pull/86 and you can try the fix for it in the version 1.1.1 1st release candidate: https://github.com/indigo-dc/udocker/releases/tag/v1.1.1-RC1

**Comment by jorge-lip** [comment]
Could you elaborate the specific case, the example below works:

 ./udocker -q run --env HOME=/home  office 
d8a08182[/]$ echo $HOME
/home

**Comment by jorge-lip** [comment]
Close fixed in 1.1.1
