### ISSUE TITLE
Add --port-map option to proot

### ISSUE THREAD

**Issue by romainreuillon** [indigo-dc/udocker#99]
proot `--port-map` makes proot transparently remap the network port between client and server. It is super useful when running several times the same client/server process concurrently on the same machine. Otherwise the it will crash because the server port is already allocated.

**Comment by romainreuillon** [comment]
My bad, I just checked in proot, port seems to be remapped by default.

**Comment by jorge-lip** [comment]
do you mean --port-map or --netcoop ?
There are some new udocker flags to take advantage of network cooperation and port  mapping
available in PRoot. In udocker these are implemented as:
 --publish=hostport:containerport | -p hostport:containerport
and
--publish-all | -P | --netcoop
